/**
 * Locale Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxLocaleApiLanguage } from '../models/RobloxLocaleApiLanguage';
import { RobloxLocaleApiSupportedLocale } from '../models/RobloxLocaleApiSupportedLocale';
import { HttpFile } from '../../../common/http/http';

export class RobloxLocaleApiUserLocaleResponse {
    'supportedLocale'?: RobloxLocaleApiSupportedLocale;
    'nativeLanguage'?: RobloxLocaleApiLanguage;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "supportedLocale",
            "baseName": "supportedLocale",
            "type": "RobloxLocaleApiSupportedLocale",
            "format": ""
        },
        {
            "name": "nativeLanguage",
            "baseName": "nativeLanguage",
            "type": "RobloxLocaleApiLanguage",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocaleApiUserLocaleResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

