/**
 * Locale Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxLocaleApiSupportedLocale } from '../models/RobloxLocaleApiSupportedLocale';
import { HttpFile } from '../../../common/http/http';

/**
* Returns list of supported locales
*/
export class RobloxLocaleApiSupportedLocalesResponse {
    /**
    * List of supported locales. Will be empty on error.
    */
    'supportedLocales'?: Array<RobloxLocaleApiSupportedLocale>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "supportedLocales",
            "baseName": "supportedLocales",
            "type": "Array<RobloxLocaleApiSupportedLocale>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocaleApiSupportedLocalesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

