/**
 * Locale Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxLocaleApiCountryRegion } from '../models/RobloxLocaleApiCountryRegion';
import { HttpFile } from '../../../common/http/http';

/**
* Returns list of supported country/regions
*/
export class RobloxLocaleApiCountryRegionListResponse {
    /**
    * List of supported country/regions. Will be empty on error.
    */
    'countryRegionList'?: Array<RobloxLocaleApiCountryRegion>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "countryRegionList",
            "baseName": "countryRegionList",
            "type": "Array<RobloxLocaleApiCountryRegion>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocaleApiCountryRegionListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

