/**
 * Avatar Api v3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxPlatformAvatarBodyColorsModelV2 {
    'headColor3'?: string;
    'torsoColor3'?: string;
    'rightArmColor3'?: string;
    'leftArmColor3'?: string;
    'rightLegColor3'?: string;
    'leftLegColor3'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "headColor3",
            "baseName": "headColor3",
            "type": "string",
            "format": ""
        },
        {
            "name": "torsoColor3",
            "baseName": "torsoColor3",
            "type": "string",
            "format": ""
        },
        {
            "name": "rightArmColor3",
            "baseName": "rightArmColor3",
            "type": "string",
            "format": ""
        },
        {
            "name": "leftArmColor3",
            "baseName": "leftArmColor3",
            "type": "string",
            "format": ""
        },
        {
            "name": "rightLegColor3",
            "baseName": "rightLegColor3",
            "type": "string",
            "format": ""
        },
        {
            "name": "leftLegColor3",
            "baseName": "leftLegColor3",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxPlatformAvatarBodyColorsModelV2.attributeTypeMap;
    }

    public constructor() {
    }
}

