/**
 * Assets Permissions API
 * Manages permissions between subjects (Universes/Groups/Users) & assets (between a variety of types)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetPermissionsCheckBatchAssetPermissions4XXResponseResultsInner } from '../models/AssetPermissionsCheckBatchAssetPermissions4XXResponseResultsInner';
import { HttpFile } from '../../../common/http/http';

export class AssetPermissionsCheckBatchAssetPermissions4XXResponse {
    'results'?: Array<AssetPermissionsCheckBatchAssetPermissions4XXResponseResultsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<AssetPermissionsCheckBatchAssetPermissions4XXResponseResultsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetPermissionsCheckBatchAssetPermissions4XXResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

