/**
 * Assets Permissions API
 * Manages permissions between subjects (Universes/Groups/Users) & assets (between a variety of types)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetPermissionAction } from '../models/AssetPermissionAction';
import { HttpFile } from '../../../common/http/http';

export class AssetPermissionItem {
    'action'?: AssetPermissionAction;
    'assetId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "AssetPermissionAction",
            "format": ""
        },
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return AssetPermissionItem.attributeTypeMap;
    }

    public constructor() {
    }
}



