/**
 * Assets API
 * Requires user authentication, not open cloud asset API; Not fully implemented
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetType } from '../models/AssetType';
import { CreationContext } from '../models/CreationContext';
import { ModerationResult } from '../models/ModerationResult';
import { Preview } from '../models/Preview';
import { HttpFile } from '../../../common/http/http';

/**
* Represents an asset.
*/
export class Asset {
    'assetType'?: AssetType;
    /**
    * The unique identifier of the asset.
    */
    'assetId'?: number;
    'creationContext'?: CreationContext;
    /**
    * The description of the asset. Limit to 1000 characters.
    */
    'description'?: string;
    /**
    * Display name of the asset.
    */
    'displayName'?: string;
    /**
    * The returned resource path of the asset.
    */
    'path'?: string;
    /**
    * Revision ID of the asset. Equivalent to `versionNumber`. Every change of the asset automatically commits a new version. The format is an integer string. Example: `1`.
    */
    'revisionId'?: string;
    /**
    * The creation timestamp of the current revision.
    */
    'revisionCreateTime'?: Date;
    'moderationResult'?: ModerationResult;
    /**
    * The resource path for the icon.
    */
    'icon'?: string;
    /**
    * A list of previews, each with an asset path and alt text. Previews must be either **Image** or **YoutubeVideo** assets.
    */
    'previews'?: Array<Preview>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetType",
            "baseName": "assetType",
            "type": "AssetType",
            "format": ""
        },
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "creationContext",
            "baseName": "creationContext",
            "type": "CreationContext",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "revisionId",
            "baseName": "revisionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "revisionCreateTime",
            "baseName": "revisionCreateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "moderationResult",
            "baseName": "moderationResult",
            "type": "ModerationResult",
            "format": ""
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string",
            "format": ""
        },
        {
            "name": "previews",
            "baseName": "previews",
            "type": "Array<Preview>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Asset.attributeTypeMap;
    }

    public constructor() {
    }
}



