/**
 * Assets Permissions API
 * Manages permissions between subjects (Universes/Groups/Users) & assets (between a variety of types)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class AssetPermissionsCopyUniversePermissions200Response {
    'operationId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "operationId",
            "baseName": "operationId",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return AssetPermissionsCopyUniversePermissions200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

