/**
 * Assets Permissions API
 * Manages permissions between subjects (Universes/Groups/Users) & assets (between a variety of types)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetBatchCheckPermissionsResponseValue } from '../models/AssetBatchCheckPermissionsResponseValue';
import { HttpFile } from '../../../common/http/http';

export class AssetBatchCheckPermissionsResponse {
    'value'?: AssetBatchCheckPermissionsResponseValue;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "AssetBatchCheckPermissionsResponseValue",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetBatchCheckPermissionsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

