/**
 * Assets API
 * Requires user authentication, not open cloud asset API; Not fully implemented
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* The asset type.
*/
export enum AssetType {
    Unspecified = 'Unspecified',
    Image = 'Image',
    Tshirt = 'Tshirt',
    Audio = 'Audio',
    Mesh = 'Mesh',
    Lua = 'Lua',
    Html = 'Html',
    Text = 'Text',
    Hat = 'Hat',
    Place = 'Place',
    Model = 'Model',
    Shirt = 'Shirt',
    Pants = 'Pants',
    Decal = 'Decal',
    Avatar = 'Avatar',
    Head = 'Head',
    Face = 'Face',
    Gear = 'Gear',
    Badge = 'Badge',
    GroupEmblem = 'GroupEmblem',
    Animation = 'Animation',
    Arms = 'Arms',
    Legs = 'Legs',
    Torso = 'Torso',
    RightArm = 'RightArm',
    LeftArm = 'LeftArm',
    LeftLeg = 'LeftLeg',
    RightLeg = 'RightLeg',
    Package = 'Package',
    YoutubeVideo = 'YoutubeVideo',
    GamePass = 'GamePass',
    App = 'App',
    Code = 'Code',
    Plugin = 'Plugin',
    SolidModel = 'SolidModel',
    MeshPart = 'MeshPart',
    HairAccessory = 'HairAccessory',
    FaceAccessory = 'FaceAccessory',
    NeckAccessory = 'NeckAccessory',
    ShoulderAccessory = 'ShoulderAccessory',
    FrontAccessory = 'FrontAccessory',
    BackAccessory = 'BackAccessory',
    WaistAccessory = 'WaistAccessory',
    ClimbAnimation = 'ClimbAnimation',
    DeathAnimation = 'DeathAnimation',
    FallAnimation = 'FallAnimation',
    IdleAnimation = 'IdleAnimation',
    JumpAnimation = 'JumpAnimation',
    RunAnimation = 'RunAnimation',
    SwimAnimation = 'SwimAnimation',
    WalkAnimation = 'WalkAnimation',
    PoseAnimation = 'PoseAnimation',
    LocalizationTableManifest = 'LocalizationTableManifest',
    LocalizationTableTranslation = 'LocalizationTableTranslation',
    EmoteAnimation = 'EmoteAnimation',
    Video = 'Video',
    TexturePack = 'TexturePack',
    TshirtAccessory = 'TshirtAccessory',
    ShirtAccessory = 'ShirtAccessory',
    PantsAccessory = 'PantsAccessory',
    JacketAccessory = 'JacketAccessory',
    SweaterAccessory = 'SweaterAccessory',
    ShortsAccessory = 'ShortsAccessory',
    LeftShoeAccessory = 'LeftShoeAccessory',
    RightShoeAccessory = 'RightShoeAccessory',
    DressSkirtAccessory = 'DressSkirtAccessory',
    FontFamily = 'FontFamily',
    FontFace = 'FontFace',
    MeshHiddenSurfaceRemoval = 'MeshHiddenSurfaceRemoval',
    EyebrowAccessory = 'EyebrowAccessory',
    EyelashAccessory = 'EyelashAccessory',
    MoodAnimation = 'MoodAnimation',
    DynamicHead = 'DynamicHead',
    CodeSnippet = 'CodeSnippet',
    AdsVideo = 'AdsVideo'
}
