/**
 * Toolbox Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class ToolBoxServiceSearchV1ResultSpellCheckerResult {
    'correctionState'?: number;
    'correctedQuery'?: string | null;
    'userQuery'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "correctionState",
            "baseName": "correctionState",
            "type": "number",
            "format": ""
        },
        {
            "name": "correctedQuery",
            "baseName": "correctedQuery",
            "type": "string",
            "format": ""
        },
        {
            "name": "userQuery",
            "baseName": "userQuery",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ToolBoxServiceSearchV1ResultSpellCheckerResult.attributeTypeMap;
    }

    public constructor() {
    }
}

