/**
 * Toolbox Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* [ \'Audio\' = 3, \'Plugin\' = 38, \'MeshPart\' = 40, \'Video\' = 62, \'FontFamily\' = 73  ] 
*/
export enum ToolBoxServiceAssetTypes {
    Audio = 3,
    Plugin = 38,
    MeshPart = 40,
    Video = 62,
    FontFamily = 73
}
