/**
 * Toolbox Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class ToolBoxServiceDetailsItemAssetAssetAudioDetails {
    'audioType'?: ToolBoxServiceDetailsItemAssetAssetAudioDetailsAudioTypeEnum;
    'artist'?: string;
    'title'?: string;
    'musicAlbum'?: string;
    'musicGenre'?: string | null;
    'soundEffectCategory'?: string;
    'soundEffectSubCatergory'?: string;
    'tags'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "audioType",
            "baseName": "audioType",
            "type": "ToolBoxServiceDetailsItemAssetAssetAudioDetailsAudioTypeEnum",
            "format": ""
        },
        {
            "name": "artist",
            "baseName": "artist",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "musicAlbum",
            "baseName": "musicAlbum",
            "type": "string",
            "format": ""
        },
        {
            "name": "musicGenre",
            "baseName": "musicGenre",
            "type": "string",
            "format": ""
        },
        {
            "name": "soundEffectCategory",
            "baseName": "soundEffectCategory",
            "type": "string",
            "format": ""
        },
        {
            "name": "soundEffectSubCatergory",
            "baseName": "soundEffectSubCatergory",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ToolBoxServiceDetailsItemAssetAssetAudioDetails.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ToolBoxServiceDetailsItemAssetAssetAudioDetailsAudioTypeEnum {
    Unknown = 'Unknown',
    Music = 'Music',
    SoundEffect = 'SoundEffect'
}

