/**
 * Toolbox Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ToolBoxServiceSearchV1ResultItem } from '../models/ToolBoxServiceSearchV1ResultItem';
import { ToolBoxServiceSearchV1ResultQueryFacets } from '../models/ToolBoxServiceSearchV1ResultQueryFacets';
import { ToolBoxServiceSearchV1ResultSpellCheckerResult } from '../models/ToolBoxServiceSearchV1ResultSpellCheckerResult';
import { HttpFile } from '../../../common/http/http';

export class ToolBoxServiceSearchV1Result {
    'totalResults'?: number;
    'filteredKeyword'?: string;
    'searchDebugInfo'?: any | null;
    'spellCheckerResult'?: ToolBoxServiceSearchV1ResultSpellCheckerResult;
    'queryFacets'?: ToolBoxServiceSearchV1ResultQueryFacets;
    'imageSearchStatus'?: string | null;
    'nextPageCursor'?: string | null;
    'previousPageCursor'?: string | null;
    'data'?: Array<ToolBoxServiceSearchV1ResultItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalResults",
            "baseName": "totalResults",
            "type": "number",
            "format": ""
        },
        {
            "name": "filteredKeyword",
            "baseName": "filteredKeyword",
            "type": "string",
            "format": ""
        },
        {
            "name": "searchDebugInfo",
            "baseName": "searchDebugInfo",
            "type": "any",
            "format": ""
        },
        {
            "name": "spellCheckerResult",
            "baseName": "spellCheckerResult",
            "type": "ToolBoxServiceSearchV1ResultSpellCheckerResult",
            "format": ""
        },
        {
            "name": "queryFacets",
            "baseName": "queryFacets",
            "type": "ToolBoxServiceSearchV1ResultQueryFacets",
            "format": ""
        },
        {
            "name": "imageSearchStatus",
            "baseName": "imageSearchStatus",
            "type": "string",
            "format": ""
        },
        {
            "name": "nextPageCursor",
            "baseName": "nextPageCursor",
            "type": "string",
            "format": ""
        },
        {
            "name": "previousPageCursor",
            "baseName": "previousPageCursor",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ToolBoxServiceSearchV1ResultItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ToolBoxServiceSearchV1Result.attributeTypeMap;
    }

    public constructor() {
    }
}

