/**
 * Toolbox Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ToolBoxServiceDetailsItemAssetFiatProductPurchasePrice } from '../models/ToolBoxServiceDetailsItemAssetFiatProductPurchasePrice';
import { HttpFile } from '../../../common/http/http';

export class ToolBoxServiceDetailsItemAssetFiatProduct {
    'purchasePrice'?: ToolBoxServiceDetailsItemAssetFiatProductPurchasePrice;
    'published'?: boolean;
    'purchasable'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "purchasePrice",
            "baseName": "purchasePrice",
            "type": "ToolBoxServiceDetailsItemAssetFiatProductPurchasePrice",
            "format": ""
        },
        {
            "name": "published",
            "baseName": "published",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "purchasable",
            "baseName": "purchasable",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ToolBoxServiceDetailsItemAssetFiatProduct.attributeTypeMap;
    }

    public constructor() {
    }
}

