/**
 * Toolbox Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class ToolBoxServiceDetailsItemAssetFiatProductPurchasePriceQuantity {
    'significand'?: number;
    'exponent'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "significand",
            "baseName": "significand",
            "type": "number",
            "format": ""
        },
        {
            "name": "exponent",
            "baseName": "exponent",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ToolBoxServiceDetailsItemAssetFiatProductPurchasePriceQuantity.attributeTypeMap;
    }

    public constructor() {
    }
}

