/**
 * Toolbox Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class ToolBoxServiceSocialLinks {
    'linkType'?: ToolBoxServiceSocialLinksLinkTypeEnum;
    'url'?: string;
    'title'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "linkType",
            "baseName": "linkType",
            "type": "ToolBoxServiceSocialLinksLinkTypeEnum",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ToolBoxServiceSocialLinks.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ToolBoxServiceSocialLinksLinkTypeEnum {
    Invalid = 'Invalid',
    Discord = 'Discord',
    Youtube = 'Youtube',
    Twitter = 'Twitter',
    Twitch = 'Twitch',
    Facebook = 'Facebook',
    Github = 'Github',
    Roblox = 'Roblox',
    Guilded = 'Guilded'
}

