/**
 * Users Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A response model representing absolute minimal authenticating user information.  No new attributes should be added to this response since it is in the critical path of app launch and we want to minimize dependencies.
*/
export class RobloxUsersApiAuthenticatedUserResponse {
    /**
    * The user Id.
    */
    'id'?: number;
    /**
    * The user name.
    */
    'name'?: string;
    /**
    * The user DisplayName.
    */
    'displayName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxUsersApiAuthenticatedUserResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

