/**
 * Economy Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* The response model for {M:Roblox.Economy.Api.Controllers.V1.CashOutController.CashOutAbility}
*/
export class RobloxEconomyApiModelsCashOutAbilityResponseModel {
    /**
    * Gets a value indicating whether the user can cash out.
    */
    'canCashOut'?: boolean;
    /**
    * Gets a value indicating whether the user meets the Premium requirement
    */
    'meetsPremiumRequirement'?: boolean;
    /**
    * Gets a value indicating whether the user has verified email address.
    */
    'hasVerifiedEmail'?: boolean;
    /**
    * Gets a value indicating whether the user is blacklisted.
    */
    'isUserBlackListed'?: boolean;
    /**
    * Gets a value indicating whether the user meets the minimum cash out balance.
    */
    'meetsMinimumCashOutBalance'?: boolean;
    /**
    * Gets a value indicating whether the user has cashed out this month.
    */
    'hasCashedOutThisMonth'?: boolean;
    /**
    * Gets a value indicating whether the user\'s last imbursement status, if any, is valid.
    */
    'lastImbursementStatusIsValid'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "canCashOut",
            "baseName": "canCashOut",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "meetsPremiumRequirement",
            "baseName": "meetsPremiumRequirement",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasVerifiedEmail",
            "baseName": "hasVerifiedEmail",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isUserBlackListed",
            "baseName": "isUserBlackListed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "meetsMinimumCashOutBalance",
            "baseName": "meetsMinimumCashOutBalance",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasCashedOutThisMonth",
            "baseName": "hasCashedOutThisMonth",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastImbursementStatusIsValid",
            "baseName": "lastImbursementStatusIsValid",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxEconomyApiModelsCashOutAbilityResponseModel.attributeTypeMap;
    }

    public constructor() {
    }
}

