/**
 * Games Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxWebResponsesRelatedEntityTypeResponseRobloxPlatformAssetsAssetType } from '../models/RobloxWebResponsesRelatedEntityTypeResponseRobloxPlatformAssetsAssetType';
import { RobloxWebResponsesRelatedEntityTypeResponseRobloxPlatformCoreCreatorType } from '../models/RobloxWebResponsesRelatedEntityTypeResponseRobloxPlatformCoreCreatorType';
import { HttpFile } from '../../../common/http/http';

/**
* A response model representing a game.
*/
export class RobloxWebResponsesGamesGameResponseV2 {
    /**
    * The game (universe) Id.
    */
    'id'?: number;
    /**
    * The game name.
    */
    'name'?: string;
    /**
    * The game description.
    */
    'description'?: string;
    'creator'?: RobloxWebResponsesRelatedEntityTypeResponseRobloxPlatformCoreCreatorType;
    'rootPlace'?: RobloxWebResponsesRelatedEntityTypeResponseRobloxPlatformAssetsAssetType;
    /**
    * When the game was created.
    */
    'created'?: Date;
    /**
    * When the game was last updated.
    */
    'updated'?: Date;
    /**
    * The number of place visits for this game.
    */
    'placeVisits'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "RobloxWebResponsesRelatedEntityTypeResponseRobloxPlatformCoreCreatorType",
            "format": ""
        },
        {
            "name": "rootPlace",
            "baseName": "rootPlace",
            "type": "RobloxWebResponsesRelatedEntityTypeResponseRobloxPlatformAssetsAssetType",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "placeVisits",
            "baseName": "placeVisits",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return RobloxWebResponsesGamesGameResponseV2.attributeTypeMap;
    }

    public constructor() {
    }
}

