/**
 * LocalizationTables Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Model containing a translation count for a language and relevant language information.
*/
export class RobloxLocalizationTablesApiLanguageTranslationCount {
    /**
    * The locale of the language.
    */
    'locale'?: string;
    /**
    * The translation count value.
    */
    'translationCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        },
        {
            "name": "translationCount",
            "baseName": "translationCount",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocalizationTablesApiLanguageTranslationCount.attributeTypeMap;
    }

    public constructor() {
    }
}

