/**
 * LocalizationTables Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxLocalizationTablesApiCursorEntryIdentifier } from '../models/RobloxLocalizationTablesApiCursorEntryIdentifier';
import { HttpFile } from '../../../common/http/http';

export class RobloxLocalizationTablesApiGetTableEntriesTranslationHistoryRequest {
    'locale'?: string;
    'entries'?: Array<RobloxLocalizationTablesApiCursorEntryIdentifier>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        },
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<RobloxLocalizationTablesApiCursorEntryIdentifier>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocalizationTablesApiGetTableEntriesTranslationHistoryRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

