/**
 * LocalizationTables Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxLocalizationTablesApiRaiseEventForAutoScrapedEntriesCleanupRequest {
    /**
    * The time range to remove entries from. Following ISO 8601 Durations format
    */
    'maxAgeForFlush'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maxAgeForFlush",
            "baseName": "maxAgeForFlush",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocalizationTablesApiRaiseEventForAutoScrapedEntriesCleanupRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

