/**
 * LocalizationTables Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxLocalizationTablesApiGameAutolocalizationInformationResponse {
    'isAutolocalizationEnabled'?: boolean;
    'isAutomaticEntriesSettingEnabled'?: boolean;
    'shouldUseLocalizationTable'?: boolean;
    'autoLocalizationTableId'?: string;
    'assetId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isAutolocalizationEnabled",
            "baseName": "isAutolocalizationEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isAutomaticEntriesSettingEnabled",
            "baseName": "isAutomaticEntriesSettingEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "shouldUseLocalizationTable",
            "baseName": "shouldUseLocalizationTable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "autoLocalizationTableId",
            "baseName": "autoLocalizationTableId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocalizationTablesApiGameAutolocalizationInformationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

