/**
 * LocalizationTables Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxLocalizationTablesApiLocalizationTablesMetadataResponse {
    /**
    * Is bulk upload feature enabled
    */
    'isBulkUploadFeatureEnabled'?: boolean;
    /**
    * Is CSV download feature enabled
    */
    'isCsvDownloadEnabled'?: boolean;
    /**
    * Is access to translation metadata feature enabled
    */
    'isAccessToTranslationMetaDataEnabled'?: boolean;
    /**
    * Is access to translation metadata feature enabled
    */
    'isTranslationManagementRedirectionEnabled'?: boolean;
    /**
    * Is untranslated filter on UI is enabled
    */
    'isUntranslatedFilterEnabled'?: boolean;
    /**
    * Is filter for automatic translations on UI is enabled
    */
    'isAutomaticTranslationFilterEnabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isBulkUploadFeatureEnabled",
            "baseName": "isBulkUploadFeatureEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isCsvDownloadEnabled",
            "baseName": "isCsvDownloadEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isAccessToTranslationMetaDataEnabled",
            "baseName": "isAccessToTranslationMetaDataEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isTranslationManagementRedirectionEnabled",
            "baseName": "isTranslationManagementRedirectionEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isUntranslatedFilterEnabled",
            "baseName": "isUntranslatedFilterEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isAutomaticTranslationFilterEnabled",
            "baseName": "isAutomaticTranslationFilterEnabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocalizationTablesApiLocalizationTablesMetadataResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

