/**
 * LocalizationTables Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxLocalizationTablesApiEntryIdentifier } from '../models/RobloxLocalizationTablesApiEntryIdentifier';
import { HttpFile } from '../../../common/http/http';

/**
* A model that contains an entry identifier and an associated cursor for paged lookups.
*/
export class RobloxLocalizationTablesApiCursorEntryIdentifier {
    /**
    * The location to begin our query.
    */
    'cursor'?: string;
    'identifier'?: RobloxLocalizationTablesApiEntryIdentifier;
    /**
    * The translation history count to get.
    */
    'count'?: number;
    /**
    * In which order the data is sorted. [\'Asc\' = 1, \'Desc\' = 2]
    */
    'sortOrder'?: RobloxLocalizationTablesApiCursorEntryIdentifierSortOrderEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "RobloxLocalizationTablesApiEntryIdentifier",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "sortOrder",
            "baseName": "sortOrder",
            "type": "RobloxLocalizationTablesApiCursorEntryIdentifierSortOrderEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocalizationTablesApiCursorEntryIdentifier.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxLocalizationTablesApiCursorEntryIdentifierSortOrderEnum {
    Asc = 'Asc',
    Desc = 'Desc'
}

