/**
 * LocalizationTables Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxLocalizationtablesLocalizationtablesV1ChangeAgent {
    /**
    *  [\'Invalid\' = 0, \'User\' = 1, \'Automation\' = 2, \'Default\' = 3]
    */
    'changeAgentType'?: RobloxLocalizationtablesLocalizationtablesV1ChangeAgentChangeAgentTypeEnum;
    'id'?: string;
    /**
    *  [\'None\' = 0, \'Id\' = 2]
    */
    'optionalIdCase'?: RobloxLocalizationtablesLocalizationtablesV1ChangeAgentOptionalIdCaseEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "changeAgentType",
            "baseName": "ChangeAgentType",
            "type": "RobloxLocalizationtablesLocalizationtablesV1ChangeAgentChangeAgentTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "Id",
            "type": "string",
            "format": ""
        },
        {
            "name": "optionalIdCase",
            "baseName": "OptionalIdCase",
            "type": "RobloxLocalizationtablesLocalizationtablesV1ChangeAgentOptionalIdCaseEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocalizationtablesLocalizationtablesV1ChangeAgent.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxLocalizationtablesLocalizationtablesV1ChangeAgentChangeAgentTypeEnum {
    Invalid = 'Invalid',
    User = 'User',
    Automation = 'Automation',
    Default = 'Default'
}
export enum RobloxLocalizationtablesLocalizationtablesV1ChangeAgentOptionalIdCaseEnum {
    None = 'None',
    Id = 'Id'
}

