/**
 * LocalizationTables Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxLocalizationTablesApiEntryTranslationFeedback } from '../models/RobloxLocalizationTablesApiEntryTranslationFeedback';
import { HttpFile } from '../../../common/http/http';

/**
* A response model for GetTableEntriesTranslationFeedback.
*/
export class RobloxLocalizationTablesApiGetTableEntriesTranslationFeedbackResponse {
    /**
    * The entries\' tableId.
    */
    'tableId'?: string;
    /**
    * The entries with their identifier, translation feedback details.
    */
    'entries'?: Array<RobloxLocalizationTablesApiEntryTranslationFeedback>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tableId",
            "baseName": "tableId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<RobloxLocalizationTablesApiEntryTranslationFeedback>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxLocalizationTablesApiGetTableEntriesTranslationFeedbackResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

