/**
 * Games Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Request model to update a VIP server.
*/
export class RobloxGamesApiVipServerUpdateRequest {
    /**
    * Server name
    */
    'name'?: string;
    /**
    * Server join code
    */
    'newJoinCode'?: boolean;
    /**
    * Server status
    */
    'active'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "newJoinCode",
            "baseName": "newJoinCode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGamesApiVipServerUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

