/**
 * Games Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxGamesApiGameResponse } from '../models/RobloxGamesApiGameResponse';
import { RobloxGamesApiVipServerPermissionsResponse } from '../models/RobloxGamesApiVipServerPermissionsResponse';
import { RobloxGamesApiVipServerSubscriptionResponse } from '../models/RobloxGamesApiVipServerSubscriptionResponse';
import { RobloxGamesApiVipServerVoiceSettingsResponse } from '../models/RobloxGamesApiVipServerVoiceSettingsResponse';
import { HttpFile } from '../../../common/http/http';

/**
* Response model for a VIP server.
*/
export class RobloxGamesApiVipServerResponse {
    /**
    * Server Id
    */
    'id'?: number;
    /**
    * Server name
    */
    'name'?: string;
    'game'?: RobloxGamesApiGameResponse;
    /**
    * Server join code
    */
    'joinCode'?: string;
    /**
    * Server status
    */
    'active'?: boolean;
    'subscription'?: RobloxGamesApiVipServerSubscriptionResponse;
    'permissions'?: RobloxGamesApiVipServerPermissionsResponse;
    'voiceSettings'?: RobloxGamesApiVipServerVoiceSettingsResponse;
    /**
    * Private server link
    */
    'link'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "game",
            "baseName": "game",
            "type": "RobloxGamesApiGameResponse",
            "format": ""
        },
        {
            "name": "joinCode",
            "baseName": "joinCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "RobloxGamesApiVipServerSubscriptionResponse",
            "format": ""
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "RobloxGamesApiVipServerPermissionsResponse",
            "format": ""
        },
        {
            "name": "voiceSettings",
            "baseName": "voiceSettings",
            "type": "RobloxGamesApiVipServerVoiceSettingsResponse",
            "format": ""
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGamesApiVipServerResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

