/**
 * Games Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Response model for getting whether a universe has private servers enabled.
*/
export class RobloxGamesApiModelsResponsePrivateServersEnabledInUniverseResponse {
    /**
    * Whether private servers are enabled in the universe.
    */
    'privateServersEnabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "privateServersEnabled",
            "baseName": "privateServersEnabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGamesApiModelsResponsePrivateServersEnabledInUniverseResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

