/**
 * Games Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Response model for getting the game creator
*/
export class RobloxGamesApiModelsResponseGameCreator {
    /**
    * The game creator id
    */
    'id'?: number;
    /**
    * The game creator name
    */
    'name'?: string;
    /**
    * The game creator type
    */
    'type'?: string;
    /**
    * The game creator account is Luobu Real Name Verified
    */
    'isRNVAccount'?: boolean;
    /**
    * Builder verified badge status.
    */
    'hasVerifiedBadge'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "isRNVAccount",
            "baseName": "isRNVAccount",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasVerifiedBadge",
            "baseName": "hasVerifiedBadge",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGamesApiModelsResponseGameCreator.attributeTypeMap;
    }

    public constructor() {
    }
}

