/**
 * Games Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Game favorite request model.
*/
export class RobloxGamesApiModelsRequestGameFavoritesRequest {
    /**
    * true for favor the game, false for unfavor the game.
    */
    'isFavorited'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isFavorited",
            "baseName": "isFavorited",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGamesApiModelsRequestGameFavoritesRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

