/**
 * Games Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* This class contains context information about a page load for the user.
*/
export class RobloxGamesApiModelsResponsePageContext {
    /**
    * Id to identify the page as shown to the user.
    */
    'pageId'?: string;
    /**
    * SortPosition
    */
    'isSeeAllPage'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pageId",
            "baseName": "pageId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "isSeeAllPage",
            "baseName": "isSeeAllPage",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGamesApiModelsResponsePageContext.attributeTypeMap;
    }

    public constructor() {
    }
}

