/**
 * Games Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Response model for getting the user vote status for a game
*/
export class RobloxGamesApiModelsResponseUserGameVoteResponse {
    /**
    * Whether the user can vote the game
    */
    'canVote'?: boolean;
    /**
    * The user\'s vote status for the game
    */
    'userVote'?: boolean;
    /**
    * The reason why the user can\'t vote
    */
    'reasonForNotVoteable'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "canVote",
            "baseName": "canVote",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userVote",
            "baseName": "userVote",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reasonForNotVoteable",
            "baseName": "reasonForNotVoteable",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGamesApiModelsResponseUserGameVoteResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

