/**
 * Presence Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxPresenceApiModelsResponseLastOnline } from '../models/RobloxPresenceApiModelsResponseLastOnline';
import { HttpFile } from '../../../common/http/http';

/**
* Last online endpoint response model.
*/
export class RobloxPresenceApiModelsResponseLastOnlineResponse {
    /**
    * List of last online timestamps.
    */
    'lastOnlineTimestamps'?: Array<RobloxPresenceApiModelsResponseLastOnline>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lastOnlineTimestamps",
            "baseName": "lastOnlineTimestamps",
            "type": "Array<RobloxPresenceApiModelsResponseLastOnline>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxPresenceApiModelsResponseLastOnlineResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

