/**
 * Presence Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Request model to Register App Presence
*/
export class RobloxPresenceApiModelsRequestRegisterAppPresenceRequest {
    /**
    * Gets or sets location
    */
    'location'?: string;
    /**
    * Gets or sets placeId
    */
    'placeId'?: number;
    /**
    * Gets or sets if session was disconnected or not
    */
    'disconnect'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "placeId",
            "baseName": "placeId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "disconnect",
            "baseName": "disconnect",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxPresenceApiModelsRequestRegisterAppPresenceRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

