/**
 * Friends Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxFriendsApiModelsResponseUserRecommendation {
    'userId'?: number;
    'userName'?: string;
    'userProfilePageUrl'?: string;
    /**
    *  [\'Offline\' = 0, \'Online\' = 1, \'InGame\' = 2, \'InStudio\' = 3, \'Invisible\' = 4]
    */
    'userPresenceType'?: RobloxFriendsApiModelsResponseUserRecommendationUserPresenceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "userProfilePageUrl",
            "baseName": "userProfilePageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "userPresenceType",
            "baseName": "userPresenceType",
            "type": "RobloxFriendsApiModelsResponseUserRecommendationUserPresenceTypeEnum",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RobloxFriendsApiModelsResponseUserRecommendation.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxFriendsApiModelsResponseUserRecommendationUserPresenceTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4
}

