/**
 * Friends Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A response model representing a friend request.
*/
export class RobloxFriendsApiFriendRequest {
    /**
    * When the friend request was sent.
    */
    'sentAt'?: Date;
    /**
    * The sender user Id.
    */
    'senderId'?: number;
    /**
    * The source universe Id which the request was sent in.
    */
    'sourceUniverseId'?: number;
    /**
    * The origin source type associated with the friend request. [\'Unknown\' = 0, \'PlayerSearch\' = 1, \'QrCode\' = 2, \'InGame\' = 3, \'UserProfile\' = 4, \'QqContactImporter\' = 5, \'WeChatContactImporter\' = 6, \'ProfileShare\' = 7, \'PhoneContactImporter\' = 8, \'FriendRecommendations\' = 9]
    */
    'originSourceType'?: RobloxFriendsApiFriendRequestOriginSourceTypeEnum;
    /**
    * The contact name associated with the friend request.
    */
    'contactName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sentAt",
            "baseName": "sentAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "senderId",
            "baseName": "senderId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sourceUniverseId",
            "baseName": "sourceUniverseId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "originSourceType",
            "baseName": "originSourceType",
            "type": "RobloxFriendsApiFriendRequestOriginSourceTypeEnum",
            "format": "int32"
        },
        {
            "name": "contactName",
            "baseName": "contactName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxFriendsApiFriendRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxFriendsApiFriendRequestOriginSourceTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9
}

