/**
 * Friends Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A response model representing user information that also contains select presence information
*/
export class RobloxFriendsApiModelsResponseUserResponse {
    /**
    * Whether the user is online.
    */
    'isOnline'?: boolean;
    /**
    * Where the user is online. [\'Offline\' = 0, \'Online\' = 1, \'InGame\' = 2, \'InStudio\' = 3, \'Invisible\' = 4]
    */
    'presenceType'?: RobloxFriendsApiModelsResponseUserResponsePresenceTypeEnum;
    /**
    * Whether the user is deleted.
    */
    'isDeleted'?: boolean;
    /**
    * Frequents value for the user.
    */
    'friendFrequentScore'?: number;
    /**
    * Frequents rank for the user.
    */
    'friendFrequentRank'?: number;
    /**
    * The user\'s verified badge status.
    */
    'hasVerifiedBadge'?: boolean;
    'description'?: string;
    'created'?: Date;
    'isBanned'?: boolean;
    'externalAppDisplayName'?: string;
    'id'?: number;
    'name'?: string;
    'displayName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isOnline",
            "baseName": "isOnline",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "presenceType",
            "baseName": "presenceType",
            "type": "RobloxFriendsApiModelsResponseUserResponsePresenceTypeEnum",
            "format": "int32"
        },
        {
            "name": "isDeleted",
            "baseName": "isDeleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "friendFrequentScore",
            "baseName": "friendFrequentScore",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "friendFrequentRank",
            "baseName": "friendFrequentRank",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "hasVerifiedBadge",
            "baseName": "hasVerifiedBadge",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isBanned",
            "baseName": "isBanned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "externalAppDisplayName",
            "baseName": "externalAppDisplayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxFriendsApiModelsResponseUserResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxFriendsApiModelsResponseUserResponsePresenceTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4
}

