/**
 * Economy Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Response model for a virtual economy transaction totals.
*/
export class RobloxEconomyApiModelsTransactionTotalsResponse {
    'salesTotal'?: number;
    'purchasesTotal'?: number;
    'affiliateSalesTotal'?: number;
    'groupPayoutsTotal'?: number;
    'currencyPurchasesTotal'?: number;
    'premiumStipendsTotal'?: number;
    'tradeSystemEarningsTotal'?: number;
    'tradeSystemCostsTotal'?: number;
    'premiumPayoutsTotal'?: number;
    'groupPremiumPayoutsTotal'?: number;
    'adSpendTotal'?: number;
    'developerExchangeTotal'?: number;
    'pendingRobuxTotal'?: number;
    'incomingRobuxTotal'?: number;
    'outgoingRobuxTotal'?: number;
    'individualToGroupTotal'?: number;
    'csAdjustmentTotal'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "salesTotal",
            "baseName": "salesTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "purchasesTotal",
            "baseName": "purchasesTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "affiliateSalesTotal",
            "baseName": "affiliateSalesTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "groupPayoutsTotal",
            "baseName": "groupPayoutsTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "currencyPurchasesTotal",
            "baseName": "currencyPurchasesTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "premiumStipendsTotal",
            "baseName": "premiumStipendsTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "tradeSystemEarningsTotal",
            "baseName": "tradeSystemEarningsTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "tradeSystemCostsTotal",
            "baseName": "tradeSystemCostsTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "premiumPayoutsTotal",
            "baseName": "premiumPayoutsTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "groupPremiumPayoutsTotal",
            "baseName": "groupPremiumPayoutsTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "adSpendTotal",
            "baseName": "adSpendTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "developerExchangeTotal",
            "baseName": "developerExchangeTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "pendingRobuxTotal",
            "baseName": "pendingRobuxTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "incomingRobuxTotal",
            "baseName": "incomingRobuxTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "outgoingRobuxTotal",
            "baseName": "outgoingRobuxTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "individualToGroupTotal",
            "baseName": "individualToGroupTotal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "csAdjustmentTotal",
            "baseName": "csAdjustmentTotal",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return RobloxEconomyApiModelsTransactionTotalsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

