/**
 * Economy Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Response model detailing the transaction types a user has used in their account lifetime.
*/
export class RobloxEconomyApiModelsTransactionUsedTypesResponse {
    'hasPurchase'?: boolean;
    'hasSale'?: boolean;
    'hasAffiliateSale'?: boolean;
    'hasGroupPayout'?: boolean;
    'hasCurrencyPurchase'?: boolean;
    'hasTradeRobux'?: boolean;
    'hasPremiumStipend'?: boolean;
    'hasEngagementPayout'?: boolean;
    'hasGroupEngagementPayout'?: boolean;
    'hasAdSpend'?: boolean;
    'hasDevEx'?: boolean;
    'hasIndividualToGroup'?: boolean;
    'hasCSAdjustment'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasPurchase",
            "baseName": "HasPurchase",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasSale",
            "baseName": "HasSale",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasAffiliateSale",
            "baseName": "HasAffiliateSale",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasGroupPayout",
            "baseName": "HasGroupPayout",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasCurrencyPurchase",
            "baseName": "HasCurrencyPurchase",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasTradeRobux",
            "baseName": "HasTradeRobux",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasPremiumStipend",
            "baseName": "HasPremiumStipend",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasEngagementPayout",
            "baseName": "HasEngagementPayout",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasGroupEngagementPayout",
            "baseName": "HasGroupEngagementPayout",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasAdSpend",
            "baseName": "HasAdSpend",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasDevEx",
            "baseName": "HasDevEx",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasIndividualToGroup",
            "baseName": "HasIndividualToGroup",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hasCSAdjustment",
            "baseName": "HasCSAdjustment",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxEconomyApiModelsTransactionUsedTypesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

