/**
 * Economy Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxPagingExclusiveStartKeyCursorSystemInt64 {
    'key'?: number;
    'sortOrder'?: RobloxPagingExclusiveStartKeyCursorSystemInt64SortOrderEnum;
    'pagingDirection'?: RobloxPagingExclusiveStartKeyCursorSystemInt64PagingDirectionEnum;
    'pageNumber'?: number;
    'discriminator'?: string;
    'count'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sortOrder",
            "baseName": "sortOrder",
            "type": "RobloxPagingExclusiveStartKeyCursorSystemInt64SortOrderEnum",
            "format": ""
        },
        {
            "name": "pagingDirection",
            "baseName": "pagingDirection",
            "type": "RobloxPagingExclusiveStartKeyCursorSystemInt64PagingDirectionEnum",
            "format": ""
        },
        {
            "name": "pageNumber",
            "baseName": "pageNumber",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "discriminator",
            "baseName": "discriminator",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RobloxPagingExclusiveStartKeyCursorSystemInt64.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxPagingExclusiveStartKeyCursorSystemInt64SortOrderEnum {
    Asc = 'Asc',
    Desc = 'Desc'
}
export enum RobloxPagingExclusiveStartKeyCursorSystemInt64PagingDirectionEnum {
    Forward = 'Forward',
    Backward = 'Backward'
}

