/**
 * Economy Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxEconomyApiModelsAgentResponse } from '../models/RobloxEconomyApiModelsAgentResponse';
import { RobloxWebResponsesEconomyGenericCurrencyResponse } from '../models/RobloxWebResponsesEconomyGenericCurrencyResponse';
import { HttpFile } from '../../../common/http/http';

/**
* Response model for a virtual economy transaction.
*/
export class RobloxEconomyApiModelsTransactionResponse {
    /**
    * The id
    */
    'id'?: number;
    /**
    * The timestamp the transaction occurred.
    */
    'created'?: Date;
    /**
    * Whether or not the transaction is pending.
    */
    'isPending'?: boolean;
    'agent'?: RobloxEconomyApiModelsAgentResponse;
    /**
    * Base class that represents the item in the transaction.
    */
    'details'?: any;
    'currency'?: RobloxWebResponsesEconomyGenericCurrencyResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isPending",
            "baseName": "isPending",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "agent",
            "baseName": "agent",
            "type": "RobloxEconomyApiModelsAgentResponse",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "any",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "RobloxWebResponsesEconomyGenericCurrencyResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxEconomyApiModelsTransactionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

