/**
 * Thumbnails Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxWebResponsesThumbnailsThumbnailBatchResponse {
    'requestId'?: string;
    'errorCode'?: number;
    'errorMessage'?: string;
    'targetId'?: number;
    /**
    *  [\'Error\' = 0, \'Completed\' = 1, \'InReview\' = 2, \'Pending\' = 3, \'Blocked\' = 4, \'TemporarilyUnavailable\' = 5]
    */
    'state'?: RobloxWebResponsesThumbnailsThumbnailBatchResponseStateEnum;
    'imageUrl'?: string;
    'version'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorCode",
            "baseName": "errorCode",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetId",
            "baseName": "targetId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "RobloxWebResponsesThumbnailsThumbnailBatchResponseStateEnum",
            "format": ""
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxWebResponsesThumbnailsThumbnailBatchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxWebResponsesThumbnailsThumbnailBatchResponseStateEnum {
    Error = 'Error',
    Completed = 'Completed',
    InReview = 'InReview',
    Pending = 'Pending',
    Blocked = 'Blocked',
    TemporarilyUnavailable = 'TemporarilyUnavailable'
}

