/**
 * Publish Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxPublishApiAssetQuota } from '../models/RobloxPublishApiAssetQuota';
import { HttpFile } from '../../../common/http/http';

/**
* Response model for asset quotas.
*/
export class RobloxPublishApiAssetQuotasResponse {
    /**
    * A list of quotas.
    */
    'quotas'?: Array<RobloxPublishApiAssetQuota>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quotas",
            "baseName": "quotas",
            "type": "Array<RobloxPublishApiAssetQuota>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxPublishApiAssetQuotasResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

