/**
 * Publish Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class SystemIOStream {
    'canRead'?: boolean;
    'canWrite'?: boolean;
    'canSeek'?: boolean;
    'canTimeout'?: boolean;
    'length'?: number;
    'position'?: number;
    'readTimeout'?: number;
    'writeTimeout'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "canRead",
            "baseName": "CanRead",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canWrite",
            "baseName": "CanWrite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canSeek",
            "baseName": "CanSeek",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canTimeout",
            "baseName": "CanTimeout",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "Length",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "position",
            "baseName": "Position",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "readTimeout",
            "baseName": "ReadTimeout",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "writeTimeout",
            "baseName": "WriteTimeout",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return SystemIOStream.attributeTypeMap;
    }

    public constructor() {
    }
}

