/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvatarCreationBody } from '../models/AvatarCreationBody';
import { AvatarCreationHead } from '../models/AvatarCreationHead';
import { HttpFile } from '../../../common/http/http';

/**
* Represents the process of creating a new avatar in the system. The resource  manages the lifecycle of avatar creation, from initial submission to  finalization, including the addition of necessary items.
*/
export class AvatarCreation {
    /**
    * The resource path of the avatar creation.  Format: avatar-creations/{avatar_creation}
    */
    'path'?: string;
    /**
    * The name of the avatar being created. This will be the final name for the  avatar. Must be non-empty. Has a maximum limit of 50 characters.
    */
    'displayName': string;
    /**
    * The description of the avatar being created. This will be the final  description for the avatar. Has a maximum limit of 1000 characters.
    */
    'description': string;
    /**
    * The creation state of the avatar creation.  Creation is a two steps process where you create and finalized  the creation by adding the assets later through AddItems call.  Possible values:    | Value | Description |   | --- | --- |   | CREATION_STATE_UNSPECIFIED | Default value. |   | CREATION_STATE_INITIALIZED | Creation is initialized. |   | CREATION_STATE_PENDING | Creation is in progress. |   | CREATION_STATE_SUCCEEDED | Creation is succeeded. |   | CREATION_STATE_FAILED | Creation is failed. |
    */
    'creationState'?: AvatarCreationCreationStateEnum;
    /**
    * The moderation state of the Avatar Body.  Possible values:    | Value | Description |   | --- | --- |   | MODERATION_STATE_UNSPECIFIED | Default value. |   | MODERATION_STATE_PENDING | Moderation is in progress. |   | MODERATION_STATE_APPROVED | Moderation is approved. |   | MODERATION_STATE_REJECTED | Moderation is rejected. |
    */
    'moderationState'?: AvatarCreationModerationStateEnum;
    /**
    * The reason of creation failure.  Possible values:    | Value | Description |   | --- | --- |   | CREATION_FAILURE_REASON_UNSPECIFIED | Default value. |   | CREATION_FAILURE_REASON_VALIDATION_FAILED | Avatar content validation is failing. |
    */
    'creationFailureReason'?: AvatarCreationCreationFailureReasonEnum;
    'body'?: AvatarCreationBody;
    'head'?: AvatarCreationHead;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "creationState",
            "baseName": "creationState",
            "type": "AvatarCreationCreationStateEnum",
            "format": "enum"
        },
        {
            "name": "moderationState",
            "baseName": "moderationState",
            "type": "AvatarCreationModerationStateEnum",
            "format": "enum"
        },
        {
            "name": "creationFailureReason",
            "baseName": "creationFailureReason",
            "type": "AvatarCreationCreationFailureReasonEnum",
            "format": "enum"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "AvatarCreationBody",
            "format": ""
        },
        {
            "name": "head",
            "baseName": "head",
            "type": "AvatarCreationHead",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvatarCreation.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AvatarCreationCreationStateEnum {
    Unspecified = 'CREATION_STATE_UNSPECIFIED',
    Initialized = 'CREATION_STATE_INITIALIZED',
    Pending = 'CREATION_STATE_PENDING',
    Succeeded = 'CREATION_STATE_SUCCEEDED',
    Failed = 'CREATION_STATE_FAILED'
}
export enum AvatarCreationModerationStateEnum {
    Unspecified = 'MODERATION_STATE_UNSPECIFIED',
    Pending = 'MODERATION_STATE_PENDING',
    Approved = 'MODERATION_STATE_APPROVED',
    Rejected = 'MODERATION_STATE_REJECTED'
}
export enum AvatarCreationCreationFailureReasonEnum {
    Unspecified = 'CREATION_FAILURE_REASON_UNSPECIFIED',
    ValidationFailed = 'CREATION_FAILURE_REASON_VALIDATION_FAILED'
}

