/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* AvatarAsset represents an asset that belongs to an avatar.
*/
export class AvatarCreationAvatarAsset {
    /**
    * Asset ID.   Format: \"assets/123\"   Note: This resource path refers to apis.roblox.com/assets.  That is,  the full URI of the asset might look like  \"apis.roblox.com/assets/v1/assets/123\".
    */
    'asset'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "asset",
            "baseName": "asset",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvatarCreationAvatarAsset.attributeTypeMap;
    }

    public constructor() {
    }
}

