/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvatarCreationAvatarAsset } from '../models/AvatarCreationAvatarAsset';
import { AvatarCreationHeadAssets } from '../models/AvatarCreationHeadAssets';
import { HttpFile } from '../../../common/http/http';

/**
* Assets that are part of a body.
*/
export class AvatarCreationBodyAssets {
    'head': AvatarCreationHeadAssets;
    'torso': AvatarCreationAvatarAsset;
    'rightArm': AvatarCreationAvatarAsset;
    'leftArm': AvatarCreationAvatarAsset;
    'rightLeg': AvatarCreationAvatarAsset;
    'leftLeg': AvatarCreationAvatarAsset;
    'hairAccessory'?: AvatarCreationAvatarAsset;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "head",
            "baseName": "head",
            "type": "AvatarCreationHeadAssets",
            "format": ""
        },
        {
            "name": "torso",
            "baseName": "torso",
            "type": "AvatarCreationAvatarAsset",
            "format": ""
        },
        {
            "name": "rightArm",
            "baseName": "rightArm",
            "type": "AvatarCreationAvatarAsset",
            "format": ""
        },
        {
            "name": "leftArm",
            "baseName": "leftArm",
            "type": "AvatarCreationAvatarAsset",
            "format": ""
        },
        {
            "name": "rightLeg",
            "baseName": "rightLeg",
            "type": "AvatarCreationAvatarAsset",
            "format": ""
        },
        {
            "name": "leftLeg",
            "baseName": "leftLeg",
            "type": "AvatarCreationAvatarAsset",
            "format": ""
        },
        {
            "name": "hairAccessory",
            "baseName": "hairAccessory",
            "type": "AvatarCreationAvatarAsset",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvatarCreationBodyAssets.attributeTypeMap;
    }

    public constructor() {
    }
}

