/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvatarAssetMeta } from '../models/AvatarAssetMeta';
import { HttpFile } from '../../../common/http/http';

/**
* AvatarAsset represents an body part asset or accessory that belongs to a  body. Need to be in sync with avatar-core source definition:  https://github.rbx.com/Roblox/avatar-core/blob/master/protos/roblox/avatarcore/outfits/v1beta1/outfits.proto#L27
*/
export class AvatarAsset {
    /**
    * Asset ID.   Format: \"assets/123\"   Note: This resource path refers to apis.roblox.com/assets.  That is,  the full URI of the asset might look like  \"apis.roblox.com/assets/v1/assets/123\".
    */
    'asset'?: string;
    'meta'?: AvatarAssetMeta;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "asset",
            "baseName": "asset",
            "type": "string",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "AvatarAssetMeta",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvatarAsset.attributeTypeMap;
    }

    public constructor() {
    }
}

