/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvatarCreationBodyAssets } from '../models/AvatarCreationBodyAssets';
import { HttpFile } from '../../../common/http/http';

/**
* Represents the body of avatars which includes assets for the head, arms,  legs, and torso.
*/
export class AvatarCreationBody {
    'assets'?: AvatarCreationBodyAssets;
    /**
    * Unique identifier of an outfit.
    */
    'outfitId'?: string;
    /**
    * Unique identifier of a bundle.
    */
    'bundleId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assets",
            "baseName": "assets",
            "type": "AvatarCreationBodyAssets",
            "format": ""
        },
        {
            "name": "outfitId",
            "baseName": "outfitId",
            "type": "string",
            "format": ""
        },
        {
            "name": "bundleId",
            "baseName": "bundleId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvatarCreationBody.attributeTypeMap;
    }

    public constructor() {
    }
}

