/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Accessory refinement property, allowing consumers to control how much an  asset is scaled with respect to its default size.
*/
export class AvatarAssetAssetScale {
    /**
    * Total scale multiplier of accessory (deprecated).
    */
    'scale'?: number;
    /**
    * X scale multiplier of accessory.
    */
    'x'?: number;
    /**
    * Y scale multiplier of accessory.
    */
    'y'?: number;
    /**
    * Z scale multiplier of accessory.
    */
    'z'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scale",
            "baseName": "scale",
            "type": "number",
            "format": "float"
        },
        {
            "name": "x",
            "baseName": "x",
            "type": "number",
            "format": "float"
        },
        {
            "name": "y",
            "baseName": "y",
            "type": "number",
            "format": "float"
        },
        {
            "name": "z",
            "baseName": "z",
            "type": "number",
            "format": "float"
        }    ];

    static getAttributeTypeMap() {
        return AvatarAssetAssetScale.attributeTypeMap;
    }

    public constructor() {
    }
}

