/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Colors of all body parts in format of Color Hex Code, E.g. \"#FFFFFF\" (white)  Need to be in sync with avatar-core source definition:  https://github.rbx.com/Roblox/avatar-core/blob/master/protos/roblox/avatarcore/outfits/v1beta1/outfits.proto#L27
*/
export class BodyColors {
    /**
    * Head color
    */
    'headColor': string;
    /**
    * Torso color
    */
    'torsoColor': string;
    /**
    * Right arm color
    */
    'rightArmColor': string;
    /**
    * Left arm color
    */
    'leftArmColor': string;
    /**
    * Right leg color
    */
    'rightLegColor': string;
    /**
    * Left leg color
    */
    'leftLegColor': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "headColor",
            "baseName": "headColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "torsoColor",
            "baseName": "torsoColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "rightArmColor",
            "baseName": "rightArmColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "leftArmColor",
            "baseName": "leftArmColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "rightLegColor",
            "baseName": "rightLegColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "leftLegColor",
            "baseName": "leftLegColor",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BodyColors.attributeTypeMap;
    }

    public constructor() {
    }
}

