/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Represents the permissions on a role.
*/
export class GroupRoleRolePermissions {
    /**
    * View group wall.
    */
    'viewWallPosts'?: boolean;
    /**
    * Post on group wall.
    */
    'createWallPosts'?: boolean;
    /**
    * Delete group wall posts.
    */
    'deleteWallPosts'?: boolean;
    /**
    * View group shout.
    */
    'viewGroupShout'?: boolean;
    /**
    * Post group shout.
    */
    'createGroupShout'?: boolean;
    /**
    * Manage lower-ranked member ranks.
    */
    'changeRank'?: boolean;
    /**
    * Accept join requests.
    */
    'acceptRequests'?: boolean;
    /**
    * Kick lower-ranked members.
    */
    'exileMembers'?: boolean;
    /**
    * Manage allies and enemies.
    */
    'manageRelationships'?: boolean;
    /**
    * View audit log.
    */
    'viewAuditLog'?: boolean;
    /**
    * Spend group funds.
    */
    'spendGroupFunds'?: boolean;
    /**
    * Advertise group.
    */
    'advertiseGroup'?: boolean;
    /**
    * Create avatar items.
    */
    'createAvatarItems'?: boolean;
    /**
    * Manage avatar items.
    */
    'manageAvatarItems'?: boolean;
    /**
    * Manage group universes.
    */
    'manageGroupUniverses'?: boolean;
    /**
    * View universe analytics.
    */
    'viewUniverseAnalytics'?: boolean;
    /**
    * Create group API Keys.
    */
    'createApiKeys'?: boolean;
    /**
    * Manage all group API keys.
    */
    'manageApiKeys'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "viewWallPosts",
            "baseName": "viewWallPosts",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createWallPosts",
            "baseName": "createWallPosts",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deleteWallPosts",
            "baseName": "deleteWallPosts",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "viewGroupShout",
            "baseName": "viewGroupShout",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createGroupShout",
            "baseName": "createGroupShout",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "changeRank",
            "baseName": "changeRank",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "acceptRequests",
            "baseName": "acceptRequests",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "exileMembers",
            "baseName": "exileMembers",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "manageRelationships",
            "baseName": "manageRelationships",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "viewAuditLog",
            "baseName": "viewAuditLog",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "spendGroupFunds",
            "baseName": "spendGroupFunds",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "advertiseGroup",
            "baseName": "advertiseGroup",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createAvatarItems",
            "baseName": "createAvatarItems",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "manageAvatarItems",
            "baseName": "manageAvatarItems",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "manageGroupUniverses",
            "baseName": "manageGroupUniverses",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "viewUniverseAnalytics",
            "baseName": "viewUniverseAnalytics",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createApiKeys",
            "baseName": "createApiKeys",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "manageApiKeys",
            "baseName": "manageApiKeys",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GroupRoleRolePermissions.attributeTypeMap;
    }

    public constructor() {
    }
}

