/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MemoryStoreQueueItem } from '../models/MemoryStoreQueueItem';
import { HttpFile } from '../../../common/http/http';

/**
* Returns the specified number of items at the front of the queue
*/
export class ReadMemoryStoreQueueItemsResponse {
    /**
    * An identifier of the read operation   This can be passed to `:discard` in order to mark the items as processed.
    */
    'readId'?: string;
    /**
    * The items read from the queue
    */
    'items'?: Array<MemoryStoreQueueItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "readId",
            "baseName": "readId",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<MemoryStoreQueueItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReadMemoryStoreQueueItemsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

