/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A secret represented as a byte array.   Secrets are software-level credentials that allow a program  to access another program without the need for providing a username and  a password.
*/
export class Secret {
    /**
    * The resource path of the secret.   Format:  universes/{universe}/secrets/{secret}
    */
    'path'?: string;
    /**
    * Secret creation timestamp.
    */
    'createTime'?: Date;
    /**
    * Timestamp when the secret was last updated.
    */
    'updateTime'?: Date;
    /**
    * The content of the secret. For example: API keys (text), private keys  (binary).
    */
    'secret'?: string;
    /**
    * Pubilc key identifier. The key with this identifier was used for sealed box  encryption.
    */
    'keyId'?: string;
    /**
    * Secret designation: domain name, or a wildcard.
    */
    'domain'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "createTime",
            "baseName": "createTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updateTime",
            "baseName": "updateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "string",
            "format": "bytes"
        },
        {
            "name": "keyId",
            "baseName": "keyId",
            "type": "string",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Secret.attributeTypeMap;
    }

    public constructor() {
    }
}

