/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Information about the specific category of an event.
*/
export class UniverseEventCategory {
    /**
    * Information about an event related to updated content within an  experience.
    */
    'contentUpdate'?: any;
    /**
    * Information about an update related to a location within an experience.
    */
    'locationUpdate'?: any;
    /**
    * Information about an update to systems and mechanics within an  experience.
    */
    'systemUpdate'?: any;
    /**
    * Information about an event related to a specific in-experience activity.
    */
    'activity'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contentUpdate",
            "baseName": "contentUpdate",
            "type": "any",
            "format": ""
        },
        {
            "name": "locationUpdate",
            "baseName": "locationUpdate",
            "type": "any",
            "format": ""
        },
        {
            "name": "systemUpdate",
            "baseName": "systemUpdate",
            "type": "any",
            "format": ""
        },
        {
            "name": "activity",
            "baseName": "activity",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UniverseEventCategory.attributeTypeMap;
    }

    public constructor() {
    }
}

