/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSocialNetworkProfiles } from '../models/UserSocialNetworkProfiles';
import { HttpFile } from '../../../common/http/http';

/**
* Represents any registered user of Roblox.
*/
export class User {
    /**
    * The resource path of the user.   Format: users/{user}
    */
    'path'?: string;
    /**
    * The timestamp at which the user was created.
    */
    'createTime'?: Date;
    /**
    * Unique ID that identifies a user in Roblox.
    */
    'id'?: string;
    /**
    * Unique username for a user in Roblox.
    */
    'name'?: string;
    /**
    * Display name for the user.
    */
    'displayName'?: string;
    /**
    * User-defined information about themselves.
    */
    'about'?: string;
    /**
    * Current locale selected by the user. Returns IETF language code.
    */
    'locale'?: string;
    /**
    * Whether the user is a premium user.   To access this data, you need an API key / OAuth token with the following  scope: user.advanced:read
    */
    'premium'?: boolean;
    /**
    * Specifies if the user is ID-verified.   To access this data, you need an API key / OAuth token with the following  scope: user.advanced:read
    */
    'idVerified'?: boolean;
    'socialNetworkProfiles'?: UserSocialNetworkProfiles;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "createTime",
            "baseName": "createTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "about",
            "baseName": "about",
            "type": "string",
            "format": ""
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        },
        {
            "name": "premium",
            "baseName": "premium",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "idVerified",
            "baseName": "idVerified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "socialNetworkProfiles",
            "baseName": "socialNetworkProfiles",
            "type": "UserSocialNetworkProfiles",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}

