/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserRestrictionLogModerator } from '../models/UserRestrictionLogModerator';
import { UserRestrictionLogRestrictionType } from '../models/UserRestrictionLogRestrictionType';
import { HttpFile } from '../../../common/http/http';

/**
* An entity capturing a state change on a type of restriction.
*/
export class UserRestrictionLog {
    /**
    * The user to which this restriction update is applied.
    */
    'user'?: string;
    /**
    * The place in which a user restriction was explicitly updated.  This field is empty if the log captures a state change applied on the  universe level.
    */
    'place'?: string;
    'moderator'?: UserRestrictionLogModerator;
    /**
    * When the change happened.
    */
    'createTime'?: Date;
    /**
    * Whether the restriction was active after the action  represented by this log.
    */
    'active'?: boolean;
    /**
    * The start time of the restriction.
    */
    'startTime'?: Date;
    /**
    * The duration of the restriction.   If not specified, the restriction is permanent.
    */
    'duration'?: string;
    /**
    * The reason the restriction was created.   This field *is not* displayed to the user.
    */
    'privateReason'?: string;
    /**
    * The user-facing reason the restriction was created.   This field *is* displayed to the user.
    */
    'displayReason'?: string;
    'restrictionType'?: UserRestrictionLogRestrictionType;
    /**
    * When true, the restriction will not be be propagated to alt accounts.   Defaults to false.
    */
    'excludeAltAccounts'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        },
        {
            "name": "place",
            "baseName": "place",
            "type": "string",
            "format": ""
        },
        {
            "name": "moderator",
            "baseName": "moderator",
            "type": "UserRestrictionLogModerator",
            "format": ""
        },
        {
            "name": "createTime",
            "baseName": "createTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string",
            "format": "duration"
        },
        {
            "name": "privateReason",
            "baseName": "privateReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayReason",
            "baseName": "displayReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "restrictionType",
            "baseName": "restrictionType",
            "type": "UserRestrictionLogRestrictionType",
            "format": ""
        },
        {
            "name": "excludeAltAccounts",
            "baseName": "excludeAltAccounts",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserRestrictionLog.attributeTypeMap;
    }

    public constructor() {
    }
}

