/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* The source of the notification.
*/
export class UserNotificationSource {
    /**
    * The universe from which the user notification is sent.
    */
    'universe'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "universe",
            "baseName": "universe",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserNotificationSource.attributeTypeMap;
    }

    public constructor() {
    }
}

