/**
 * Cloud API
 * Open Cloud 2.0
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserNotificationPayloadAnalyticsData } from '../models/UserNotificationPayloadAnalyticsData';
import { UserNotificationPayloadJoinExperience } from '../models/UserNotificationPayloadJoinExperience';
import { UserNotificationPayloadParameterValue } from '../models/UserNotificationPayloadParameterValue';
import { HttpFile } from '../../../common/http/http';

/**
* Details about the notification.
*/
export class UserNotificationPayload {
    /**
    * The type of notification.  Possible values:    | Value | Description |   | --- | --- |   | TYPE_UNSPECIFIED | The default value. This value is unused. |   | MOMENT | A notification type representing a moment. |
    */
    'type'?: UserNotificationPayloadTypeEnum;
    /**
    * An ID that represents a customizable notification message template  that you create in Creator Dashboard.   The message can contain customizable parameters that you can specify  values for. For example, `Your {egg_name} just hatched` has an  `egg_name` parameter. See the `parameters` field for more  information.
    */
    'messageId'?: string;
    /**
    * A map of parameters used to render a notification message template.   For example, given a template of `Your {egg_name} just hatched.` with  parameters of `[{\"egg_name\": {\"string_value\": \"royal egg\"}}]`, the  rendered notification message is: `Your royal egg just hatched.`
    */
    'parameters'?: { [key: string]: UserNotificationPayloadParameterValue; };
    'joinExperience'?: UserNotificationPayloadJoinExperience;
    'analyticsData'?: UserNotificationPayloadAnalyticsData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "UserNotificationPayloadTypeEnum",
            "format": "enum"
        },
        {
            "name": "messageId",
            "baseName": "messageId",
            "type": "string",
            "format": ""
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "{ [key: string]: UserNotificationPayloadParameterValue; }",
            "format": ""
        },
        {
            "name": "joinExperience",
            "baseName": "joinExperience",
            "type": "UserNotificationPayloadJoinExperience",
            "format": ""
        },
        {
            "name": "analyticsData",
            "baseName": "analyticsData",
            "type": "UserNotificationPayloadAnalyticsData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserNotificationPayload.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserNotificationPayloadTypeEnum {
    TypeUnspecified = 'TYPE_UNSPECIFIED',
    Moment = 'MOMENT'
}

