/**
 * Inventory Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A model containing information about a Roblox.Platform.AssetOwnership.UserAsset
*/
export class RobloxInventoryApiModelsCollectibleUserAssetModel {
    /**
    * The user asset id
    */
    'userAssetId'?: number;
    /**
    * The serial number of the user asset
    */
    'serialNumber'?: number;
    /**
    * The asset id of the user asset
    */
    'assetId'?: number;
    /**
    * The asset name of the asset
    */
    'name'?: string;
    /**
    * The recent average price of the asset
    */
    'recentAveragePrice'?: number;
    /**
    * The original price of the asset
    */
    'originalPrice'?: number;
    /**
    * The recent average price of the user asset
    */
    'assetStock'?: number;
    /**
    * The recent average price of the user asset [\'None\' = 0, \'BC\' = 1, \'TBC\' = 2, \'OBC\' = 3, \'RobloxPremium\' = 4]
    */
    'buildersClubMembershipType'?: RobloxInventoryApiModelsCollectibleUserAssetModelBuildersClubMembershipTypeEnum;
    /**
    * Whether the user asset has an active hold.
    */
    'isOnHold'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userAssetId",
            "baseName": "userAssetId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "serialNumber",
            "baseName": "serialNumber",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "recentAveragePrice",
            "baseName": "recentAveragePrice",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "originalPrice",
            "baseName": "originalPrice",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "assetStock",
            "baseName": "assetStock",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "buildersClubMembershipType",
            "baseName": "buildersClubMembershipType",
            "type": "RobloxInventoryApiModelsCollectibleUserAssetModelBuildersClubMembershipTypeEnum",
            "format": "int32"
        },
        {
            "name": "isOnHold",
            "baseName": "isOnHold",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxInventoryApiModelsCollectibleUserAssetModel.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxInventoryApiModelsCollectibleUserAssetModelBuildersClubMembershipTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4
}

