/**
 * Inventory Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxInventoryApiAssetsExplorerCategoryItemModel {
    'name'?: string;
    'displayName'?: string;
    'filter'?: string;
    'id'?: number;
    /**
    * Describes what type an AssetsExplorerCategoryItemModel contains [\'AssetType\' = 0, \'Bundle\' = 1, \'Outfit\' = 2, \'Set\' = 3]
    */
    'type'?: RobloxInventoryApiAssetsExplorerCategoryItemModelTypeEnum;
    'categoryType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RobloxInventoryApiAssetsExplorerCategoryItemModelTypeEnum",
            "format": "int32"
        },
        {
            "name": "categoryType",
            "baseName": "categoryType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxInventoryApiAssetsExplorerCategoryItemModel.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxInventoryApiAssetsExplorerCategoryItemModelTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}

