/**
 * ItemConfiguration Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Defines the configuration options associated with releasing an item
*/
export class RobloxItemConfigurationApiReleaseConfigurationResponseModel {
    /**
    * Get or sets the sale availability locations list
    */
    'saleAvailabilityLocations'?: Array<RobloxItemConfigurationApiReleaseConfigurationResponseModelSaleAvailabilityLocationsEnum>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "saleAvailabilityLocations",
            "baseName": "saleAvailabilityLocations",
            "type": "Array<RobloxItemConfigurationApiReleaseConfigurationResponseModelSaleAvailabilityLocationsEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxItemConfigurationApiReleaseConfigurationResponseModel.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxItemConfigurationApiReleaseConfigurationResponseModelSaleAvailabilityLocationsEnum {
    Undefined = 'Undefined',
    Catalog = 'Catalog',
    AllUniverses = 'AllUniverses',
    MyUniverses = 'MyUniverses'
}

