/**
 * ItemConfiguration Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Item-tags related metadata response model
*/
export class RobloxItemConfigurationApiItemTagsMetadataResponse {
    /**
    * Gets or sets a value indicating whether the item tags feature is enabled
    */
    'isItemTagsFeatureEnabled'?: boolean;
    /**
    * Gets or sets the asset types where item tagging is enabled.
    */
    'enabledAssetTypes'?: Array<string>;
    /**
    * Gets or sets the maximum item tags per item limit
    */
    'maximumItemTagsPerItem'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isItemTagsFeatureEnabled",
            "baseName": "isItemTagsFeatureEnabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "enabledAssetTypes",
            "baseName": "enabledAssetTypes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "maximumItemTagsPerItem",
            "baseName": "maximumItemTagsPerItem",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RobloxItemConfigurationApiItemTagsMetadataResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

