/**
 * ItemConfiguration Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Defines the configuration options for an items price
*/
export class RobloxItemConfigurationApiPriceConfigurationModel {
    /**
    * Gets or sets the standard price of the item in Robux
    */
    'priceInRobux'?: number;
    /**
    * Gets or sets the discount rate on the price of the item that is given to premium users  Should not be used while applying a PremiumPriceInRobux
    */
    'premiumDiscountPercentage'?: number;
    /**
    * Gets or sets the price of the item in Robux that applies only to premium users  Should not be used while applying a PremiumDiscountPercentage
    */
    'premiumPriceInRobux'?: number;
    /**
    * Gets or sets the price offset of the item in Robux above the price floor.
    */
    'priceOffset'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "priceInRobux",
            "baseName": "priceInRobux",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "premiumDiscountPercentage",
            "baseName": "premiumDiscountPercentage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "premiumPriceInRobux",
            "baseName": "premiumPriceInRobux",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "priceOffset",
            "baseName": "priceOffset",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return RobloxItemConfigurationApiPriceConfigurationModel.attributeTypeMap;
    }

    public constructor() {
    }
}

