/**
 * ItemConfiguration Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxItemConfigurationApiCommissionRatesModel } from '../models/RobloxItemConfigurationApiCommissionRatesModel';
import { RobloxItemConfigurationApiItemTypeDetails } from '../models/RobloxItemConfigurationApiItemTypeDetails';
import { HttpFile } from '../../../common/http/http';

export class RobloxItemConfigurationApiCommissionRatesResponse {
    'itemTypeDetails'?: RobloxItemConfigurationApiItemTypeDetails;
    'commissionRates'?: RobloxItemConfigurationApiCommissionRatesModel;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "itemTypeDetails",
            "baseName": "itemTypeDetails",
            "type": "RobloxItemConfigurationApiItemTypeDetails",
            "format": ""
        },
        {
            "name": "commissionRates",
            "baseName": "commissionRates",
            "type": "RobloxItemConfigurationApiCommissionRatesModel",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxItemConfigurationApiCommissionRatesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

