/**
 * ItemConfiguration Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxItemConfigurationApiTagDetails } from '../models/RobloxItemConfigurationApiTagDetails';
import { HttpFile } from '../../../common/http/http';

export class RobloxItemConfigurationApiItemTagDetails {
    /**
    * Gets or sets the item tag id
    */
    'id'?: string;
    'tag'?: RobloxItemConfigurationApiTagDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "RobloxItemConfigurationApiTagDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxItemConfigurationApiItemTagDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

