export * from "./models/all";

export { AvatarV2ApiV2AvatarAvatarGetRequest, AvatarV2ApiV2AvatarSetBodyColorsPostRequest, AvatarV2ApiV2AvatarSetWearingAssetsPostRequest, AvatarV2ApiV2AvatarUsersUserIdAvatarGetRequest, AvatarV2ApiV2AvatarUsersUserIdOutfitsGetRequest, ObjectAvatarV2Api as AvatarV2Api,  OutfitsV2ApiV2OutfitsCreatePostRequest, OutfitsV2ApiV2OutfitsUserOutfitIdPatchRequest, OutfitsV2ApiV2OutfitsUserOutfitIdUpdatePostRequest, ObjectOutfitsV2Api as OutfitsV2Api } from './types/ObjectParamAPI';

