/**
 * Groups Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxGroupsApiGroupRoleResponse } from '../models/RobloxGroupsApiGroupRoleResponse';
import { RobloxGroupsApiModelsResponseUserModel } from '../models/RobloxGroupsApiModelsResponseUserModel';
import { HttpFile } from '../../../common/http/http';

/**
* A user group role response model
*/
export class RobloxGroupsApiUserGroupRoleResponse {
    'user'?: RobloxGroupsApiModelsResponseUserModel;
    'role'?: RobloxGroupsApiGroupRoleResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "RobloxGroupsApiModelsResponseUserModel",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "RobloxGroupsApiGroupRoleResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGroupsApiUserGroupRoleResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

