/**
 * Standard Data Stores
 * This page includes reference documentation for working with standard data stores. For more information on using the API, see [Handling API Requests for Data Stores](../../../cloud/open-cloud/data-store-api-handling.md) and the [Usage Guide](../../../cloud/open-cloud/usage-data-stores.md).
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class EntriesGetEntryVersionAsync200Response {
    /**
    * The time at which the entry was created.
    */
    'robloxEntryCreatedTime'?: Date;
    /**
    * The time at which this particular version was created.
    */
    'lastModified'?: Date;
    /**
    * The version of the returned entry.
    */
    'robloxEntryVersion'?: HttpFile;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "robloxEntryCreatedTime",
            "baseName": "roblox-entry-created-time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastModified",
            "baseName": "last-modified",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "robloxEntryVersion",
            "baseName": "roblox-entry-version",
            "type": "HttpFile",
            "format": "binary"
        }    ];

    static getAttributeTypeMap() {
        return EntriesGetEntryVersionAsync200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

