/**
 * Groups Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A request model for joining group.
*/
export class RobloxGroupsApiJoinGroupRequest {
    'sessionId'?: string;
    'redemptionToken'?: string;
    'captchaId'?: string;
    'captchaToken'?: string;
    'captchaProvider'?: string;
    'challengeId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sessionId",
            "baseName": "sessionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "redemptionToken",
            "baseName": "redemptionToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "captchaId",
            "baseName": "captchaId",
            "type": "string",
            "format": ""
        },
        {
            "name": "captchaToken",
            "baseName": "captchaToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "captchaProvider",
            "baseName": "captchaProvider",
            "type": "string",
            "format": ""
        },
        {
            "name": "challengeId",
            "baseName": "challengeId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGroupsApiJoinGroupRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

