/**
 * Groups Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxGroupsApiGroupNameChangeConfigurationResponse {
    /**
    * The cost of renaming a group
    */
    'cost'?: number;
    /**
    * The cooldown for group name changes in days
    */
    'cooldownInDays'?: number;
    /**
    * The ownership cooldown for group name changes in days
    */
    'ownershipCooldownInDays'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "cooldownInDays",
            "baseName": "cooldownInDays",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ownershipCooldownInDays",
            "baseName": "ownershipCooldownInDays",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RobloxGroupsApiGroupNameChangeConfigurationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

