/**
 * Groups Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A social link response from a create request
*/
export class RobloxGroupsApiSocialLinkResponse {
    /**
    * The id of the social link
    */
    'id'?: number;
    /**
    * What type of social media (including Roblox Group) this points to [\'Facebook\' = 0, \'Twitter\' = 1, \'YouTube\' = 2, \'Twitch\' = 3, \'GooglePlus\' = 4, \'Discord\' = 5, \'RobloxGroup\' = 6, \'Amazon\' = 7, \'Guilded\' = 8]
    */
    'type'?: RobloxGroupsApiSocialLinkResponseTypeEnum;
    /**
    * The url of the link
    */
    'url'?: string;
    /**
    * The title of the link
    */
    'title'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RobloxGroupsApiSocialLinkResponseTypeEnum",
            "format": "int32"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGroupsApiSocialLinkResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxGroupsApiSocialLinkResponseTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8
}

