/**
 * Groups Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A model representing group posts permissions
*/
export class RobloxGroupsApiGroupPostsPermissionsModel {
    /**
    * View wall permission
    */
    'viewWall'?: boolean;
    /**
    * Post to wall permission
    */
    'postToWall'?: boolean;
    /**
    * Delete from wall permission
    */
    'deleteFromWall'?: boolean;
    /**
    * View status permission
    */
    'viewStatus'?: boolean;
    /**
    * Post to status permission
    */
    'postToStatus'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "viewWall",
            "baseName": "viewWall",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "postToWall",
            "baseName": "postToWall",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deleteFromWall",
            "baseName": "deleteFromWall",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "viewStatus",
            "baseName": "viewStatus",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "postToStatus",
            "baseName": "postToStatus",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGroupsApiGroupPostsPermissionsModel.attributeTypeMap;
    }

    public constructor() {
    }
}

