/**
 * Groups Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A model representing data about an Roblox.Platform.Membership.IUser
*/
export class RobloxGroupsApiGroupMembershipPermissionsModel {
    /**
    * View wall permission
    */
    'changeRank'?: boolean;
    /**
    * Post to wall permission
    */
    'inviteMembers'?: boolean;
    /**
    * Delete from wall permission
    */
    'removeMembers'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "changeRank",
            "baseName": "changeRank",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "inviteMembers",
            "baseName": "inviteMembers",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "removeMembers",
            "baseName": "removeMembers",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxGroupsApiGroupMembershipPermissionsModel.attributeTypeMap;
    }

    public constructor() {
    }
}

