/**
 * Avatar Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxApiAvatarModelsAssetWearModel } from '../models/RobloxApiAvatarModelsAssetWearModel';
import { HttpFile } from '../../../common/http/http';

/**
* A model that contains a list of AssetWear models
*/
export class RobloxApiAvatarModelsWearRequestModel {
    /**
    * The asset ids
    */
    'assets'?: Array<RobloxApiAvatarModelsAssetWearModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<RobloxApiAvatarModelsAssetWearModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxApiAvatarModelsWearRequestModel.attributeTypeMap;
    }

    public constructor() {
    }
}

