/**
 * Avatar Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxApiAvatarModelsAssetModelV2 } from '../models/RobloxApiAvatarModelsAssetModelV2';
import { RobloxApiAvatarModelsBodyColors3Model } from '../models/RobloxApiAvatarModelsBodyColors3Model';
import { RobloxApiAvatarModelsEmoteResponseModel } from '../models/RobloxApiAvatarModelsEmoteResponseModel';
import { RobloxWebResponsesAvatarScaleModel } from '../models/RobloxWebResponsesAvatarScaleModel';
import { HttpFile } from '../../../common/http/http';

/**
* A model containing details about an avatar
*/
export class RobloxApiAvatarModelsAvatarModelV3 {
    'scales'?: RobloxWebResponsesAvatarScaleModel;
    /**
    * The avatar type [\'R6\' = 1, \'R15\' = 3]
    */
    'playerAvatarType'?: RobloxApiAvatarModelsAvatarModelV3PlayerAvatarTypeEnum;
    'bodyColor3s'?: RobloxApiAvatarModelsBodyColors3Model;
    /**
    * The assets worn on the character
    */
    'assets'?: Array<RobloxApiAvatarModelsAssetModelV2>;
    /**
    * Whether default clothing has been applied to this avatar.
    */
    'defaultShirtApplied'?: boolean;
    /**
    * Whether default clothing has been applied to this avatar.
    */
    'defaultPantsApplied'?: boolean;
    /**
    * The emotes on the character
    */
    'emotes'?: Array<RobloxApiAvatarModelsEmoteResponseModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scales",
            "baseName": "scales",
            "type": "RobloxWebResponsesAvatarScaleModel",
            "format": ""
        },
        {
            "name": "playerAvatarType",
            "baseName": "playerAvatarType",
            "type": "RobloxApiAvatarModelsAvatarModelV3PlayerAvatarTypeEnum",
            "format": "int32"
        },
        {
            "name": "bodyColor3s",
            "baseName": "bodyColor3s",
            "type": "RobloxApiAvatarModelsBodyColors3Model",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<RobloxApiAvatarModelsAssetModelV2>",
            "format": ""
        },
        {
            "name": "defaultShirtApplied",
            "baseName": "defaultShirtApplied",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "defaultPantsApplied",
            "baseName": "defaultPantsApplied",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "emotes",
            "baseName": "emotes",
            "type": "Array<RobloxApiAvatarModelsEmoteResponseModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxApiAvatarModelsAvatarModelV3.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxApiAvatarModelsAvatarModelV3PlayerAvatarTypeEnum {
    NUMBER_1 = 1,
    NUMBER_3 = 3
}

