/**
 * Avatar Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxApiAvatarModelsAssetWearModel } from '../models/RobloxApiAvatarModelsAssetWearModel';
import { RobloxApiAvatarModelsBodyColorsModel } from '../models/RobloxApiAvatarModelsBodyColorsModel';
import { RobloxWebResponsesAvatarScaleModel } from '../models/RobloxWebResponsesAvatarScaleModel';
import { HttpFile } from '../../../common/http/http';

/**
* A model containing details needed to update or create an outfit
*/
export class RobloxApiAvatarModelsOutfitUpdateModelV2 {
    /**
    * The outfit name
    */
    'name'?: string;
    'bodyColors'?: RobloxApiAvatarModelsBodyColorsModel;
    /**
    * Array of assets
    */
    'assets'?: Array<RobloxApiAvatarModelsAssetWearModel>;
    'scale'?: RobloxWebResponsesAvatarScaleModel;
    /**
    * The avatar scale
    */
    'playerAvatarType'?: string;
    /**
    * The type of outfit [\'Invalid\' = 0, \'Avatar\' = 1, \'DynamicHead\' = 2, \'InExperienceBody\' = 3]
    */
    'outfitType'?: RobloxApiAvatarModelsOutfitUpdateModelV2OutfitTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "bodyColors",
            "baseName": "bodyColors",
            "type": "RobloxApiAvatarModelsBodyColorsModel",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<RobloxApiAvatarModelsAssetWearModel>",
            "format": ""
        },
        {
            "name": "scale",
            "baseName": "scale",
            "type": "RobloxWebResponsesAvatarScaleModel",
            "format": ""
        },
        {
            "name": "playerAvatarType",
            "baseName": "playerAvatarType",
            "type": "string",
            "format": ""
        },
        {
            "name": "outfitType",
            "baseName": "outfitType",
            "type": "RobloxApiAvatarModelsOutfitUpdateModelV2OutfitTypeEnum",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RobloxApiAvatarModelsOutfitUpdateModelV2.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxApiAvatarModelsOutfitUpdateModelV2OutfitTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}

