/**
 * Badges Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxBadgesApiUniverseResponse } from '../models/RobloxBadgesApiUniverseResponse';
import { RobloxWebResponsesBadgesBadgeAwardStatisticsResponse } from '../models/RobloxWebResponsesBadgesBadgeAwardStatisticsResponse';
import { HttpFile } from '../../../common/http/http';

/**
* A response containing badge information.
*/
export class RobloxBadgesApiBadgeResponse {
    /**
    * The badge Id.
    */
    'id'?: number;
    /**
    * The name of the badge.
    */
    'name'?: string;
    /**
    * The badge description.
    */
    'description'?: string;
    /**
    * The localized name of the badge.
    */
    'displayName'?: string;
    /**
    * The localized badge description.
    */
    'displayDescription'?: string;
    /**
    * Whether or not the badge is enabled.
    */
    'enabled'?: boolean;
    /**
    * The badge icon asset Id.
    */
    'iconImageId'?: number;
    /**
    * The localized badge icon asset Id.
    */
    'displayIconImageId'?: number;
    /**
    * When the badge was created.
    */
    'created'?: Date;
    /**
    * When the badge was updated.
    */
    'updated'?: Date;
    'statistics'?: RobloxWebResponsesBadgesBadgeAwardStatisticsResponse;
    'awardingUniverse'?: RobloxBadgesApiUniverseResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayDescription",
            "baseName": "displayDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "iconImageId",
            "baseName": "iconImageId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "displayIconImageId",
            "baseName": "displayIconImageId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "statistics",
            "baseName": "statistics",
            "type": "RobloxWebResponsesBadgesBadgeAwardStatisticsResponse",
            "format": ""
        },
        {
            "name": "awardingUniverse",
            "baseName": "awardingUniverse",
            "type": "RobloxBadgesApiUniverseResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxBadgesApiBadgeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

