/**
 * Badges Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Metadata about badges.
*/
export class RobloxBadgesApiBadgeMetadataResponse {
    /**
    * The cost in Robux for creating a new badge.
    */
    'badgeCreationPrice'?: number;
    /**
    * The max length for a badge name.
    */
    'maxBadgeNameLength'?: number;
    /**
    * The max length for a badge description.
    */
    'maxBadgeDescriptionLength'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "badgeCreationPrice",
            "baseName": "badgeCreationPrice",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "maxBadgeNameLength",
            "baseName": "maxBadgeNameLength",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maxBadgeDescriptionLength",
            "baseName": "maxBadgeDescriptionLength",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RobloxBadgesApiBadgeMetadataResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

