/**
 * Badges Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* The result of being awarded a badge.
*/
export class RobloxBadgesApiBadgeAwardResponse {
    /**
    * The badge Id.
    */
    'badgeId'?: number;
    /**
    * When the badge was awarded.
    */
    'awardedDate'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "badgeId",
            "baseName": "badgeId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "awardedDate",
            "baseName": "awardedDate",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return RobloxBadgesApiBadgeAwardResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

