/**
 * Badges Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxWebResponsesBadgesBadgeAwardStatisticsResponse {
    'pastDayAwardedCount'?: number;
    'awardedCount'?: number;
    'winRatePercentage'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pastDayAwardedCount",
            "baseName": "pastDayAwardedCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "awardedCount",
            "baseName": "awardedCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "winRatePercentage",
            "baseName": "winRatePercentage",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return RobloxWebResponsesBadgesBadgeAwardStatisticsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

