/**
 * Develop Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Represents a universe in API endpoint results.
*/
export class RobloxApiDevelopModelsUniverseModel {
    /**
    * The universe Id.
    */
    'id'?: number;
    /**
    * The name of the universe
    */
    'name'?: string;
    /**
    * The description of the universe
    */
    'description'?: string;
    /**
    * Is this universe archived
    */
    'isArchived'?: boolean;
    /**
    * The universe\'s root place id
    */
    'rootPlaceId'?: number;
    /**
    * Is this universe active
    */
    'isActive'?: boolean;
    /**
    * The universe\'s privacy type.
    */
    'privacyType'?: string;
    /**
    * The creator type, either \"User\" or \"Group\"
    */
    'creatorType'?: string;
    /**
    * The id of the user or group that created this universe.
    */
    'creatorTargetId'?: number;
    /**
    * The name of the creator of the universe.
    */
    'creatorName'?: string;
    /**
    * The created System.DateTime
    */
    'created'?: Date;
    /**
    * The updated System.DateTime
    */
    'updated'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "isArchived",
            "baseName": "isArchived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rootPlaceId",
            "baseName": "rootPlaceId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "privacyType",
            "baseName": "privacyType",
            "type": "string",
            "format": ""
        },
        {
            "name": "creatorType",
            "baseName": "creatorType",
            "type": "string",
            "format": ""
        },
        {
            "name": "creatorTargetId",
            "baseName": "creatorTargetId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "creatorName",
            "baseName": "creatorName",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return RobloxApiDevelopModelsUniverseModel.attributeTypeMap;
    }

    public constructor() {
    }
}

