/**
 * Avatar Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxApiAvatarModelsBodyColorsModel } from '../models/RobloxApiAvatarModelsBodyColorsModel';
import { RobloxWebResponsesAvatarScaleModel } from '../models/RobloxWebResponsesAvatarScaleModel';
import { HttpFile } from '../../../common/http/http';

/**
* A model containing details needed to update or create an outfit
*/
export class RobloxApiAvatarModelsOutfitUpdateModelV1 {
    /**
    * The outfit name
    */
    'name'?: string;
    'bodyColors'?: RobloxApiAvatarModelsBodyColorsModel;
    /**
    * The outfit asset IDs
    */
    'assetIds'?: Array<number>;
    'scale'?: RobloxWebResponsesAvatarScaleModel;
    /**
    * The avatar scale
    */
    'playerAvatarType'?: string;
    /**
    * The type of outfit [\'Invalid\' = 0, \'Avatar\' = 1, \'DynamicHead\' = 2, \'InExperienceBody\' = 3]
    */
    'outfitType'?: RobloxApiAvatarModelsOutfitUpdateModelV1OutfitTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "bodyColors",
            "baseName": "bodyColors",
            "type": "RobloxApiAvatarModelsBodyColorsModel",
            "format": ""
        },
        {
            "name": "assetIds",
            "baseName": "assetIds",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "scale",
            "baseName": "scale",
            "type": "RobloxWebResponsesAvatarScaleModel",
            "format": ""
        },
        {
            "name": "playerAvatarType",
            "baseName": "playerAvatarType",
            "type": "string",
            "format": ""
        },
        {
            "name": "outfitType",
            "baseName": "outfitType",
            "type": "RobloxApiAvatarModelsOutfitUpdateModelV1OutfitTypeEnum",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RobloxApiAvatarModelsOutfitUpdateModelV1.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxApiAvatarModelsOutfitUpdateModelV1OutfitTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}

