/**
 * Avatar Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel } from '../models/RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel';
import { RobloxWebResponsesAvatarScaleModel } from '../models/RobloxWebResponsesAvatarScaleModel';
import { HttpFile } from '../../../common/http/http';

/**
* The game start info
*/
export class RobloxApiAvatarModelsGameStartInfoResponse {
    /**
    * Avatar Type
    */
    'gameAvatarType'?: string;
    /**
    * Custom animation enabled
    */
    'allowCustomAnimations'?: string;
    /**
    * collision type for the univers
    */
    'universeAvatarCollisionType'?: string;
    /**
    * Body type for the univers
    */
    'universeAvatarBodyType'?: string;
    /**
    * Joing positioning type
    */
    'jointPositioningType'?: string;
    /**
    * Mesasge
    */
    'message'?: string;
    'universeAvatarMinScales'?: RobloxWebResponsesAvatarScaleModel;
    'universeAvatarMaxScales'?: RobloxWebResponsesAvatarScaleModel;
    /**
    * asset overrides for the univers
    */
    'universeAvatarAssetOverrides'?: Array<RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel>;
    /**
    * Moderation status
    */
    'moderationStatus'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "gameAvatarType",
            "baseName": "gameAvatarType",
            "type": "string",
            "format": ""
        },
        {
            "name": "allowCustomAnimations",
            "baseName": "allowCustomAnimations",
            "type": "string",
            "format": ""
        },
        {
            "name": "universeAvatarCollisionType",
            "baseName": "universeAvatarCollisionType",
            "type": "string",
            "format": ""
        },
        {
            "name": "universeAvatarBodyType",
            "baseName": "universeAvatarBodyType",
            "type": "string",
            "format": ""
        },
        {
            "name": "jointPositioningType",
            "baseName": "jointPositioningType",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "universeAvatarMinScales",
            "baseName": "universeAvatarMinScales",
            "type": "RobloxWebResponsesAvatarScaleModel",
            "format": ""
        },
        {
            "name": "universeAvatarMaxScales",
            "baseName": "universeAvatarMaxScales",
            "type": "RobloxWebResponsesAvatarScaleModel",
            "format": ""
        },
        {
            "name": "universeAvatarAssetOverrides",
            "baseName": "universeAvatarAssetOverrides",
            "type": "Array<RobloxApiAvatarModelsUniverseAvatarAssetOverrideResponseModel>",
            "format": ""
        },
        {
            "name": "moderationStatus",
            "baseName": "moderationStatus",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxApiAvatarModelsGameStartInfoResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

