/**
 * Avatar Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* A model containing details about an asset type and its business rules
*/
export class RobloxApiAvatarModelsAssetTypeRulesModel {
    /**
    * The max number of this asset type that can be worn
    */
    'maxNumber'?: number;
    /**
    * The id
    */
    'id'?: number;
    /**
    * The name
    */
    'name'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maxNumber",
            "baseName": "maxNumber",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxApiAvatarModelsAssetTypeRulesModel.attributeTypeMap;
    }

    public constructor() {
    }
}

