/**
 * Avatar Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxApiAvatarModelsAssetModelV2 } from '../models/RobloxApiAvatarModelsAssetModelV2';
import { RobloxApiAvatarModelsBodyColorsModel } from '../models/RobloxApiAvatarModelsBodyColorsModel';
import { RobloxApiAvatarModelsEmoteResponseModel } from '../models/RobloxApiAvatarModelsEmoteResponseModel';
import { RobloxWebResponsesAvatarScaleModel } from '../models/RobloxWebResponsesAvatarScaleModel';
import { HttpFile } from '../../../common/http/http';

/**
* A model containing details about an avatar
*/
export class RobloxApiAvatarModelsAvatarModelV2 {
    'scales'?: RobloxWebResponsesAvatarScaleModel;
    /**
    * The avatar type [\'R6\' = 1, \'R15\' = 3]
    */
    'playerAvatarType'?: RobloxApiAvatarModelsAvatarModelV2PlayerAvatarTypeEnum;
    'bodyColors'?: RobloxApiAvatarModelsBodyColorsModel;
    /**
    * The assets worn on the character
    */
    'assets'?: Array<RobloxApiAvatarModelsAssetModelV2>;
    /**
    * Whether default clothing has been applied to this avatar.
    */
    'defaultShirtApplied'?: boolean;
    /**
    * Whether default clothing has been applied to this avatar.
    */
    'defaultPantsApplied'?: boolean;
    /**
    * The emotes on the character
    */
    'emotes'?: Array<RobloxApiAvatarModelsEmoteResponseModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scales",
            "baseName": "scales",
            "type": "RobloxWebResponsesAvatarScaleModel",
            "format": ""
        },
        {
            "name": "playerAvatarType",
            "baseName": "playerAvatarType",
            "type": "RobloxApiAvatarModelsAvatarModelV2PlayerAvatarTypeEnum",
            "format": "int32"
        },
        {
            "name": "bodyColors",
            "baseName": "bodyColors",
            "type": "RobloxApiAvatarModelsBodyColorsModel",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<RobloxApiAvatarModelsAssetModelV2>",
            "format": ""
        },
        {
            "name": "defaultShirtApplied",
            "baseName": "defaultShirtApplied",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "defaultPantsApplied",
            "baseName": "defaultPantsApplied",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "emotes",
            "baseName": "emotes",
            "type": "Array<RobloxApiAvatarModelsEmoteResponseModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxApiAvatarModelsAvatarModelV2.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxApiAvatarModelsAvatarModelV2PlayerAvatarTypeEnum {
    NUMBER_1 = 1,
    NUMBER_3 = 3
}

