/**
 * Catalog Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxAvatarCatalogSearchClientElasticsearchDebugInfo } from '../models/RobloxAvatarCatalogSearchClientElasticsearchDebugInfo';
import { RobloxCatalogApiCatalogSearchResponseItem } from '../models/RobloxCatalogApiCatalogSearchResponseItem';
import { HttpFile } from '../../../common/http/http';

/**
* ApiPageResponse for catalog search
*/
export class RobloxCatalogApiCatalogSearchPageResponseRobloxCatalogApiCatalogSearchResponseItem {
    /**
    * Keyword used for search query
    */
    'keyword'?: string;
    'elasticsearchDebugInfo'?: RobloxAvatarCatalogSearchClientElasticsearchDebugInfo;
    'previousPageCursor'?: string;
    'nextPageCursor'?: string;
    'data'?: Array<RobloxCatalogApiCatalogSearchResponseItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keyword",
            "baseName": "keyword",
            "type": "string",
            "format": ""
        },
        {
            "name": "elasticsearchDebugInfo",
            "baseName": "elasticsearchDebugInfo",
            "type": "RobloxAvatarCatalogSearchClientElasticsearchDebugInfo",
            "format": ""
        },
        {
            "name": "previousPageCursor",
            "baseName": "previousPageCursor",
            "type": "string",
            "format": ""
        },
        {
            "name": "nextPageCursor",
            "baseName": "nextPageCursor",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<RobloxCatalogApiCatalogSearchResponseItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxCatalogApiCatalogSearchPageResponseRobloxCatalogApiCatalogSearchResponseItem.attributeTypeMap;
    }

    public constructor() {
    }
}

