/**
 * Catalog Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Defines the Premium pricing for a catalog item
*/
export class RobloxCatalogApiPremiumPricingModel {
    /**
    * The Premium discount percentage for a catalog item
    */
    'premiumDiscountPercentage'?: number;
    /**
    * The Premium price for a catalog item
    */
    'premiumPriceInRobux'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "premiumDiscountPercentage",
            "baseName": "premiumDiscountPercentage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "premiumPriceInRobux",
            "baseName": "premiumPriceInRobux",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return RobloxCatalogApiPremiumPricingModel.attributeTypeMap;
    }

    public constructor() {
    }
}

