/**
 * Catalog Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxCatalogApiBundleDetailsModel } from '../models/RobloxCatalogApiBundleDetailsModel';
import { HttpFile } from '../../../common/http/http';

/**
* A response containing favorited bundles and whether there are more.
*/
export class RobloxCatalogApiFavoriteBundlesResponse {
    /**
    * Collection of favorited bundles and associated details.
    */
    'favorites'?: Array<RobloxCatalogApiBundleDetailsModel>;
    /**
    * True if there exists a next page of favorited bundles.
    */
    'moreFavorites'?: boolean;
    /**
    * Pagination cursor for the next page.
    */
    'nextCursor'?: string;
    /**
    * Pagination cursor for the previous page.
    */
    'previousCursor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "favorites",
            "baseName": "favorites",
            "type": "Array<RobloxCatalogApiBundleDetailsModel>",
            "format": ""
        },
        {
            "name": "moreFavorites",
            "baseName": "moreFavorites",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "nextCursor",
            "baseName": "nextCursor",
            "type": "string",
            "format": ""
        },
        {
            "name": "previousCursor",
            "baseName": "previousCursor",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxCatalogApiFavoriteBundlesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

