/**
 * Catalog Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

export class RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64 {
    'key'?: number;
    /**
    *  [\'Asc\' = 1, \'Desc\' = 2]
    */
    'sortOrder'?: RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64SortOrderEnum;
    /**
    *  [\'Forward\' = 1, \'Backward\' = 2]
    */
    'pagingDirection'?: RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64PagingDirectionEnum;
    'pageNumber'?: number;
    'discriminator'?: string;
    'count'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sortOrder",
            "baseName": "sortOrder",
            "type": "RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64SortOrderEnum",
            "format": "int32"
        },
        {
            "name": "pagingDirection",
            "baseName": "pagingDirection",
            "type": "RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64PagingDirectionEnum",
            "format": "int32"
        },
        {
            "name": "pageNumber",
            "baseName": "pageNumber",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "discriminator",
            "baseName": "discriminator",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64SortOrderEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}
export enum RobloxPagingExclusiveStartKeyCursorSystemNullableSystemInt64PagingDirectionEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}

