/**
 * Catalog Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxCatalogApiTopicsTopicModel } from '../models/RobloxCatalogApiTopicsTopicModel';
import { RobloxMarketplacetopicdiscoveryTopicdiscoveryserviceV1Beta1Error } from '../models/RobloxMarketplacetopicdiscoveryTopicdiscoveryserviceV1Beta1Error';
import { HttpFile } from '../../../common/http/http';

export class RobloxCatalogApiTopicsTopicResponse {
    'topics'?: Array<RobloxCatalogApiTopicsTopicModel>;
    'error'?: RobloxMarketplacetopicdiscoveryTopicdiscoveryserviceV1Beta1Error;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "topics",
            "baseName": "topics",
            "type": "Array<RobloxCatalogApiTopicsTopicModel>",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "RobloxMarketplacetopicdiscoveryTopicdiscoveryserviceV1Beta1Error",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxCatalogApiTopicsTopicResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

