/**
 * Catalog Api v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RobloxCatalogApiMultigetItemDetailsRequestItem } from '../models/RobloxCatalogApiMultigetItemDetailsRequestItem';
import { HttpFile } from '../../../common/http/http';

export class RobloxCatalogApiMultigetItemDetailsRequestModel {
    'items'?: Array<RobloxCatalogApiMultigetItemDetailsRequestItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<RobloxCatalogApiMultigetItemDetailsRequestItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxCatalogApiMultigetItemDetailsRequestModel.attributeTypeMap;
    }

    public constructor() {
    }
}

