/**
 * Develop Api v2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../../../common/http/http';

/**
* Model of an asset version.
*/
export class RobloxApiDevelopAssetVersion {
    /**
    * The VersionID of the asset version.
    */
    'id'?: number;
    /**
    * The ID of the asset.
    */
    'assetId'?: number;
    /**
    * The version number.
    */
    'assetVersionNumber'?: number;
    /**
    * Type of the asset version creator.
    */
    'creatorType'?: string;
    /**
    * ID of the asset version creator.
    */
    'creatorTargetId'?: number;
    /**
    * ID of the universe this asset version was created in.
    */
    'creatingUniverseId'?: number;
    /**
    * The created date of this asset version.
    */
    'created'?: Date;
    /**
    * Indicates if this version is same to current published version.  This property is available on /v1/{assetId}/published-versions and /v1/{assetId}/version/{versionNumber}.
    */
    'isEqualToCurrentPublishedVersion'?: boolean;
    /**
    * Indicates if this version is / was published.  This property is available on /v1/{assetId}/saved-versions.
    */
    'isPublished'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "Id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "assetVersionNumber",
            "baseName": "assetVersionNumber",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "creatorType",
            "baseName": "creatorType",
            "type": "string",
            "format": ""
        },
        {
            "name": "creatorTargetId",
            "baseName": "creatorTargetId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "creatingUniverseId",
            "baseName": "creatingUniverseId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isEqualToCurrentPublishedVersion",
            "baseName": "isEqualToCurrentPublishedVersion",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPublished",
            "baseName": "isPublished",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RobloxApiDevelopAssetVersion.attributeTypeMap;
    }

    public constructor() {
    }
}

